import type { Locale } from "@/data/site.config";

export type ServiceLine = "real-estate" | "home-inspection" | "spatial-consultation";
export type ContentItem = { title: string; slug: string; description: string; locale: Locale; publishedAt: string; updatedAt?: string; author: string; serviceLine: ServiceLine; categories: string[]; tags: string[]; featuredImage?: string; videoUrl?: string; videoPlatform?: "youtube" | "tiktok" | "instagram" | "facebook"; transcript?: string; body: string[]; cta: { label: string; href: string }; relatedContent: string[]; seo: { title: string; description: string }; demo: boolean };

export const guides: ContentItem[] = [
  { title: "What Buyers Should Look For Before Making an Offer", slug: "what-buyers-should-look-for", description: "A calm, practical walkthrough of condition, context, and daily use.", locale: "en", publishedAt: "2026-07-01", author: "Anh Cao", serviceLine: "real-estate", categories: ["Buyers"], tags: ["Georgia", "Checklist"], body: ["Notice the property beyond finishes. Look at drainage, maintenance patterns, access, noise, natural light, and whether the layout supports your routine.", "A showing is a first observation—not a substitute for professional due diligence."], cta: { label: "Plan your home purchase", href: "/en/real-estate/buyers" }, relatedContent: ["how-to-read-an-inspection-report"], seo: { title: "What Buyers Should Look For", description: "An educational home showing checklist for Georgia buyers." }, demo: true },
  { title: "How to Read a Home Inspection Report", slug: "how-to-read-an-inspection-report", description: "Separate safety, major systems, maintenance, and specialist follow-up.", locale: "en", publishedAt: "2026-07-02", author: "Anh Cao", serviceLine: "home-inspection", categories: ["Reports"], tags: ["Inspection", "Education"], body: ["Start with safety and major system concerns, then separate immediate follow-up from routine maintenance.", "Ask what was visible, what was inaccessible, and which observations need evaluation by a qualified specialist."], cta: { label: "Explore report review", href: "/en/home-inspection/sample-report" }, relatedContent: ["roof-age-vs-condition"], seo: { title: "How to Read an Inspection Report", description: "A practical framework for understanding a home inspection report." }, demo: true },
  { title: "How Layout Affects Daily Living", slug: "how-layout-affects-daily-living", description: "Evaluate circulation, privacy, light, placement, and functional zones.", locale: "en", publishedAt: "2026-07-03", author: "Anh Cao", serviceLine: "spatial-consultation", categories: ["Space"], tags: ["Layout", "Feng Shui"], body: ["A useful spatial review begins with observable facts: movement paths, light, noise, storage, privacy, and room relationships.", "Traditional Feng Shui can add an interpretive layer, but practical comfort and function remain the first priority."], cta: { label: "Book a space audit", href: "/en/spatial-consultation/space-audit" }, relatedContent: [], seo: { title: "How Layout Affects Daily Living", description: "A practical and interpretive way to evaluate home layout." }, demo: true },
];

export function contentForLocale(locale: Locale) { return guides.map((item) => locale === "en" ? item : ({ ...item, locale: "vi" as const, title: ({"what-buyers-should-look-for":"Người mua nên quan sát gì trước khi ra giá","how-to-read-an-inspection-report":"Cách đọc báo cáo kiểm tra nhà","how-layout-affects-daily-living":"Bố cục ảnh hưởng đời sống hằng ngày thế nào"} as Record<string,string>)[item.slug], description: "Nội dung giáo dục song ngữ đang được chủ website duyệt và mở rộng.", body: ["Bắt đầu từ dữ kiện quan sát được, sau đó phân loại rủi ro, nhu cầu kiểm tra thêm và ảnh hưởng thực tế đến sinh hoạt.", "Nội dung này mang tính giáo dục; quyết định quan trọng cần được xác minh với chuyên gia phù hợp."], cta: { ...item.cta, href: item.cta.href.replace("/en/", "/vi/") } })); }
