import { notFound } from "next/navigation";
import { AddToCartButton } from "@/components/cart-client";
import { featureFlags, platformConfig } from "@/data/platform.config";
import { LocalCatalogRepository } from "@/lib/catalog/repository";
import { isPublicCatalogItem } from "@/lib/catalog/types";
import { isLocale } from "@/lib/i18n";
import { formatMoney, money } from "@/lib/platform/money";
export default async function Page({ params }: { params: Promise<{ locale: string; slug: string }> }) { const { locale, slug } = await params; if (!isLocale(locale) || !featureFlags.commerceEnabled) notFound(); const item = await new LocalCatalogRepository().findBySlug(slug); if (!item || !isPublicCatalogItem(item, locale)) notFound(); const content = item.localeContent[locale]!; return <article className="product-page"><header><small>{item.type} · {item.availability}</small><h1>{content.title}</h1><p>{content.shortDescription}</p>{item.priceMinor !== null && <strong>{formatMoney(money(item.priceMinor), locale)}</strong>}</header><div className="product-description"><p>{content.description}</p></div>{item.type === "affiliate" && item.affiliate ? <><a className="button button-accent" href={item.affiliate.url} target="_blank" rel="sponsored nofollow noopener">{locale === "vi" ? `Xem tại ${item.affiliate.merchant}` : `View at ${item.affiliate.merchant}`}</a><p className="affiliate-disclosure">{item.affiliate.disclosure || platformConfig.affiliateDisclosure[locale]}</p></> : item.type === "service" && item.service ? <a className="button button-accent" href={`/${locale}/book?service=${encodeURIComponent(item.service.bookingServiceKey)}`}>{item.service.pricingModel === "free-inquiry" ? (locale === "vi" ? "Gửi yêu cầu miễn phí" : "Start a free inquiry") : (locale === "vi" ? "Yêu cầu đặt lịch" : "Request booking")}</a> : item.priceMinor !== null && (item.type === "physical" || item.type === "digital") ? <AddToCartButton item={{ id: item.id, title: content.title, priceMinor: item.priceMinor, type: item.type }} locale={locale}/> : null}</article>; }

