import {NextResponse} from "next/server";
import {z} from "zod";
import {listMediaSections,saveMediaSections} from "@/lib/media/composition";
import {compositionPageSchema,mediaSectionSchema,sectionTypeSchema} from "@/lib/media/composition-types";
import {getStudioAccess} from "@/lib/media/security";
const actionSchema=z.discriminatedUnion("action",[z.object({action:z.literal("add"),page:compositionPageSchema,type:sectionTypeSchema,assetId:z.string().optional()}),z.object({action:z.literal("toggle"),id:z.string()}),z.object({action:z.literal("move"),id:z.string(),direction:z.enum(["up","down"])}),z.object({action:z.literal("remove"),id:z.string()})]);
function denied(){return NextResponse.json({ok:false,error:getStudioAccess().reason},{status:403})}
export async function GET(){if(!getStudioAccess().enabled)return denied();return NextResponse.json({ok:true,sections:await listMediaSections()})}
export async function POST(request:Request){if(!getStudioAccess().writable)return denied();try{const body=actionSchema.parse(await request.json()),items=await listMediaSections();if(body.action==="add")items.push(mediaSectionSchema.parse({id:crypto.randomUUID(),page:body.page,type:body.type,assetIds:body.assetId?[body.assetId]:[],enabled:false,order:items.filter(item=>item.page===body.page).length}));if(body.action==="toggle"){const item=items.find(entry=>entry.id===body.id);if(item)item.enabled=!item.enabled}if(body.action==="remove")items.splice(items.findIndex(item=>item.id===body.id),1);if(body.action==="move"){const pageItem=items.find(item=>item.id===body.id);if(pageItem){const ordered=items.filter(item=>item.page===pageItem.page).sort((a,b)=>a.order-b.order),index=ordered.findIndex(item=>item.id===body.id),swap=body.direction==="up"?index-1:index+1;if(ordered[swap]){[ordered[index].order,ordered[swap].order]=[ordered[swap].order,ordered[index].order]}}}await saveMediaSections(items);return NextResponse.json({ok:true,sections:items})}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"Composition update failed."},{status:400})}}
