import {mkdtemp,rm} from "node:fs/promises";import os from "node:os";import path from "node:path";import {afterEach,describe,expect,it} from "vitest";
import {LocalContentRepository,contentReferences,publicContent,relatedContent} from "@/lib/content-studio/repository";import type {ContentEntry} from "@/lib/content-studio/types";import {LocalMediaStorageProvider} from "@/lib/media/storage";import {createEmbed} from "@/lib/embeds/storage";
const roots:string[]=[];async function root(){const value=await mkdtemp(path.join(os.tmpdir(),"spatial-content-"));roots.push(value);return value}afterEach(async()=>{await Promise.all(roots.splice(0).map(value=>rm(value,{recursive:true,force:true})))});const png=Buffer.from([137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,2,0,0,0,3,8,6,0,0,0]);
function draft(overrides:Partial<Omit<ContentEntry,"id"|"createdAt"|"updatedAt"|"publishedAt">>={}){return {type:"article",status:"draft",slug:"qa-content",serviceCategory:"general",localeContent:{en:{title:"QA Content",excerpt:"QA excerpt",blocks:[],transcript:"",seo:{title:"",description:"",canonicalOverride:"",index:true}}},publishedLocales:[],featuredImageId:null,featuredEmbedId:null,tags:[],featured:false,taxonomy:[],...overrides} as Omit<ContentEntry,"id"|"createdAt"|"updatedAt"|"publishedAt">}
describe("ContentRepository lifecycle",()=>{
 it("creates and edits stable content without changing its slug",async()=>{const repo=new LocalContentRepository(await root());const created=await repo.create(draft());const edited=await repo.update(created.id,{localeContent:{...created.localeContent,en:{...created.localeContent.en!,title:"Edited title"}}});expect(edited.slug).toBe("qa-content");expect(edited.localeContent.en?.title).toBe("Edited title")});
 it("keeps drafts private, publishes, unpublishes, and archives",async()=>{const directory=await root(),repo=new LocalContentRepository(directory);const created=await repo.create(draft());expect(await publicContent({locale:"en"},directory)).toHaveLength(0);const published=await repo.update(created.id,{status:"published",publishedLocales:["en"]});expect(published.publishedAt).toBeTruthy();expect(await publicContent({locale:"en"},directory)).toHaveLength(1);await repo.update(created.id,{status:"draft"});expect(await publicContent({locale:"en"},directory)).toHaveLength(0);const archived=await repo.update(created.id,{status:"archived"});expect(archived.status).toBe("archived");expect(await publicContent({},directory)).toHaveLength(0)});
 it("rejects duplicate slugs",async()=>{const repo=new LocalContentRepository(await root());await repo.create(draft());await expect(repo.create(draft({localeContent:{vi:{title:"Khác",excerpt:"",blocks:[],transcript:"",seo:{title:"",description:"",canonicalOverride:"",index:true}}}}))).rejects.toThrow(/Slug/)});
 it("publishes locales independently",async()=>{const directory=await root(),repo=new LocalContentRepository(directory);const item=await repo.create(draft({localeContent:{en:draft().localeContent.en,vi:{title:"Nội dung QA",excerpt:"",blocks:[],transcript:"",seo:{title:"",description:"",canonicalOverride:"",index:true}}}}));await repo.update(item.id,{status:"published",publishedLocales:["vi"]});expect(await publicContent({locale:"en"},directory)).toHaveLength(0);expect(await publicContent({locale:"vi"},directory)).toHaveLength(1)});
 it("validates and reports media and embed references",async()=>{const directory=await root(),media=new LocalMediaStorageProvider(directory);const asset=await media.upload({buffer:png,filename:"qa.png",mimeType:"image/png"});const embed=await createEmbed({url:"https://youtu.be/dQw4w9WgXcQ"},directory);const repo=new LocalContentRepository(directory);const item=await repo.create(draft({featuredImageId:asset.id,featuredEmbedId:embed.id}));expect((await contentReferences("media",asset.id,directory))[0].id).toBe(item.id);expect((await contentReferences("embed",embed.id,directory))[0].id).toBe(item.id);await expect(repo.update(item.id,{featuredImageId:"missing"})).rejects.toThrow(/media asset/)});
 it("filters public content by service and type",async()=>{const directory=await root(),repo=new LocalContentRepository(directory);const item=await repo.create(draft({type:"video",serviceCategory:"deal"}));await repo.update(item.id,{status:"published",publishedLocales:["en"]});expect(await publicContent({locale:"en",type:"video",serviceCategory:"deal"},directory)).toHaveLength(1);expect(await publicContent({locale:"en",serviceCategory:"condition"},directory)).toHaveLength(0)});
 it("ranks deterministic related content by service and shared tags",async()=>{const directory=await root(),repo=new LocalContentRepository(directory);const current=await repo.create(draft({slug:"current",serviceCategory:"deal",tags:["Georgia"]}));const related=await repo.create(draft({slug:"related",serviceCategory:"deal",tags:["Georgia"]}));await repo.update(current.id,{status:"published",publishedLocales:["en"]});await repo.update(related.id,{status:"published",publishedLocales:["en"]});expect((await relatedContent(current,"en",3,directory))[0].id).toBe(related.id)});
});
