import {mkdtemp,readFile,rm} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {afterEach,describe,expect,it} from "vitest";
import {parseEmbedInput} from "@/lib/embeds/parser";
import {assignEmbed,createEmbed,deleteEmbed,getAssignedEmbed,listEmbeds} from "@/lib/embeds/storage";

const roots:string[]=[];async function root(){const value=await mkdtemp(path.join(os.tmpdir(),"spatial-embeds-"));roots.push(value);return value}afterEach(async()=>{delete process.env.EMBED_ALLOWED_HOSTS;await Promise.all(roots.splice(0).map(value=>rm(value,{recursive:true,force:true})))});
describe("safe embed parsing",()=>{
 it("normalizes YouTube watch and short URLs",()=>{expect(parseEmbedInput({url:"https://www.youtube.com/watch?v=dQw4w9WgXcQ&utm_source=test"})).toMatchObject({provider:"youtube",contentType:"video",embedUrl:"https://www.youtube.com/embed/dQw4w9WgXcQ",autoplay:false});expect(parseEmbedInput({url:"https://youtu.be/dQw4w9WgXcQ"}).sourceUrl).toBe("https://www.youtube.com/watch?v=dQw4w9WgXcQ")});
 it("parses a YouTube playlist",()=>{expect(parseEmbedInput({url:"https://www.youtube.com/playlist?list=PL1234567890ABCDE"})).toMatchObject({contentType:"playlist",embedUrl:"https://www.youtube.com/embed/videoseries?list=PL1234567890ABCDE"})});
 it("maps YouTube Music when possible and safely links otherwise",()=>{expect(parseEmbedInput({url:"https://music.youtube.com/watch?v=dQw4w9WgXcQ"}).renderMode).toBe("iframe");expect(parseEmbedInput({url:"https://music.youtube.com/channel/example"}).renderMode).toBe("externalLink")});
 it("parses supported Spotify content",()=>{expect(parseEmbedInput({url:"https://open.spotify.com/track/4cOdK2wGLETKBW3PvgPWqT?si=test"})).toMatchObject({provider:"spotify",contentType:"audio",embedUrl:"https://open.spotify.com/embed/track/4cOdK2wGLETKBW3PvgPWqT"});expect(parseEmbedInput({url:"https://open.spotify.com/show/1234567890ABCDEF"}).contentType).toBe("podcast")});
 it("handles SoundCloud tracks and sets",()=>{expect(parseEmbedInput({url:"https://soundcloud.com/artist/track"})).toMatchObject({provider:"soundcloud",contentType:"audio"});expect(parseEmbedInput({url:"https://soundcloud.com/artist/sets/collection"}).contentType).toBe("playlist")});
 it("rejects unsafe, unsupported, and non-allowlisted URLs",()=>{expect(()=>parseEmbedInput({url:"javascript:alert(1)"})).toThrow(/HTTPS/);expect(()=>parseEmbedInput({url:"https://unknown.example/video"})).toThrow(/EMBED_ALLOWED_HOSTS/);expect(()=>parseEmbedInput({url:"https://youtube.com/watch?v=bad"})).toThrow(/valid video/)});
 it("allows only an explicitly configured custom iframe host",()=>{process.env.EMBED_ALLOWED_HOSTS="media.example.com";expect(parseEmbedInput({url:"https://media.example.com/player/1",allowedPermissions:["fullscreen"]})).toMatchObject({provider:"customIframe",allowedPermissions:["fullscreen"]});expect(()=>parseEmbedInput({url:"https://sub.media.example.com/player/1"})).toThrow(/EMBED_ALLOWED_HOSTS/)});
});
describe("embed storage and slots",()=>{it("saves, assigns, resolves, and deletes an embed",async()=>{const directory=await root();const embed=await createEmbed({url:"https://youtu.be/dQw4w9WgXcQ",title:{en:"Video",vi:"Video"}},directory);expect(await listEmbeds(directory)).toHaveLength(1);await assignEmbed("homepage.featuredEmbed",embed.id,directory);expect((await getAssignedEmbed("homepage.featuredEmbed",directory))?.embed.id).toBe(embed.id);await deleteEmbed(embed.id,directory);expect(await getAssignedEmbed("homepage.featuredEmbed",directory)).toBeNull()})});
describe("responsive embed contract",()=>{it("keeps players bounded and provides tablet and mobile layouts",async()=>{const css=await readFile(path.join(process.cwd(),"src","app","globals.css"),"utf8");expect(css).toContain(".safe-embed{margin:0;max-width:100%;overflow:hidden}");expect(css).toContain(".safe-embed iframe{display:block;width:100%;height:100%;border:0");expect(css).toContain("@media(max-width:900px){.embed-studio-intro,.embed-composer{grid-template-columns:1fr}");expect(css).toContain("@media(max-width:600px){.studio-embeds{padding-inline:1.25rem}")})});
