import {readFile} from "node:fs/promises";import path from "node:path";import {describe,expect,it} from "vitest";import {backdropFallback,canAssign,classifyAsset,detectOrientation,isVerticalNineSixteen,mediaTypeFor,normalizeSourcePath,readImageDimensions,sniffImageExtension,stripPngMetadata} from "../scripts/media-ingestion-core.mjs";
describe("local media ingestion",()=>{
  it("preserves a Windows source path with spaces and Vietnamese characters",()=>{expect(normalizeSourcePath("E:\\Real Estate\\Ảnh\\Up lên website")).toBe("E:\\Real Estate\\Ảnh\\Up lên website")});
  it("extracts PNG metadata and detects 9:16 orientation",()=>{const png=Buffer.alloc(24);png.writeUInt32BE(1080,16);png.writeUInt32BE(1920,20);expect(readImageDimensions(png,".png")).toEqual({width:1080,height:1920});expect(detectOrientation(1080,1920)).toBe("vertical-9-16");expect(isVerticalNineSixteen(1080,1920)).toBe(true)});
  it("detects image content independently from a misleading extension",()=>{const png=Buffer.alloc(24);Buffer.from([137,80,78,71,13,10,26,10]).copy(png);png.writeUInt32BE(4000,16);png.writeUInt32BE(6000,20);expect(sniffImageExtension(png)).toBe(".png");expect(readImageDimensions(png,".jpg")).toEqual({width:4000,height:6000})});
  it("removes textual and EXIF metadata from public PNG derivatives",()=>{const signature=Buffer.from([137,80,78,71,13,10,26,10]);const chunk=(type,data=Buffer.alloc(0))=>{const result=Buffer.alloc(12+data.length);result.writeUInt32BE(data.length);result.write(type,4);data.copy(result,8);return result};const source=Buffer.concat([signature,chunk("tEXt",Buffer.from("GPS=33,-84")),chunk("IDAT"),chunk("IEND")]);const cleaned=stripPngMetadata(source);expect(cleaned.includes(Buffer.from("GPS=33,-84"))).toBe(false);expect(cleaned.includes(Buffer.from("IDAT"))).toBe(true)});
  it("rejects unsupported types and preserves privacy classification",()=>{expect(mediaTypeFor(".exe")).toBe("unsupported");expect(classifyAsset("client-contract.png",1200,1600,1000)).toMatchObject({possiblePrivateInformation:true,approvedForPublicUse:false})});
  it("protects assignments unless replacement is explicit",()=>{expect(canAssign({existing:{slot:"x"}})).toBe(false);expect(canAssign({existing:{slot:"x"},replace:true})).toBe(true);expect(canAssign({existing:null})).toBe(true)});
  it("uses a static reduced-motion fallback and leaves disabled mode absent",()=>{expect(backdropFallback("scroll-pan-image",true)).toBe("static-image");expect(backdropFallback("none",false)).toBe("none")});
  it("keeps the footer outside the story backdrop shell",async()=>{const layout=await readFile(path.join(process.cwd(),"src","app","[locale]","layout.tsx"),"utf8");expect(layout.indexOf("</StoryBackdropShell>")).toBeGreaterThan(-1);expect(layout.indexOf("<Footer")).toBeGreaterThan(layout.indexOf("</StoryBackdropShell>"))});
});
