import {mkdtemp,mkdir,rm,writeFile} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {afterEach,describe,expect,it} from "vitest";
import {importInboxItem,listInbox,updateInboxDecision} from "@/lib/media/inbox";
import {mediaSlots} from "@/lib/media/types";
const roots:string[]=[];async function setup(){const root=await mkdtemp(path.join(os.tmpdir(),"media-inbox-")),source=path.join(root,"source");roots.push(root);await mkdir(path.join(root,".dev-data","media-scan"),{recursive:true});await mkdir(source);const image=path.join(source,"IMG_0228[1] transparent.JPG"),video=path.join(source,"Real Estate Outro Video For Socials.mp4");await writeFile(image,Buffer.from("png-data"));await writeFile(video,Buffer.from("video-data"));await writeFile(path.join(root,".dev-data","media-scan","manifest.json"),JSON.stringify({source,entries:[entry("portrait",image,"image","image/png","portrait","unreviewed"),entry("video",video,"video","video/mp4","unknown","needs-conversion")]}));return root}afterEach(async()=>Promise.all(roots.splice(0).map(root=>rm(root,{recursive:true,force:true}))));
function entry(id:string,sourcePath:string,mediaType:"image"|"video",mimeType:string,orientation:string,status:string){return {id,checksum:id,sourcePath,filename:path.basename(sourcePath),extension:path.extname(sourcePath),mediaType,mimeType,width:mediaType==="image"?4000:0,height:mediaType==="image"?6000:0,duration:null,aspectRatio:null,orientation,fileSize:10,detectedContext:"unknown",recommendedService:"general",recommendedSlots:[],confidence:"low",possiblePrivateInformation:false,notes:[],available:true,status}}
describe("owner-controlled media inbox",()=>{it("shows all supported scanned files including video and conversion status",async()=>{const root=await setup(),items=await listInbox(root);expect(items).toHaveLength(2);expect(items.find(item=>item.mediaType==="video")?.status).toBe("needs-conversion")});it("allows an owner to override automated classification without public approval",async()=>{const root=await setup(),result=await importInboxItem("portrait","compass-portrait","space",root);expect(result.asset).toMatchObject({mediaRole:"compass-portrait",serviceLens:"space",approvedForPublicUse:false,privacyReviewed:false});expect((await listInbox(root)).find(item=>item.id==="portrait")?.status).toBe("imported")});it("preserves explicit private decisions",async()=>{const root=await setup();await updateInboxDecision("portrait",{status:"private",ownerRole:null,ownerServiceLens:null},root);expect((await listInbox(root)).find(item=>item.id==="portrait")?.status).toBe("private")});it("groups required page slots without replacing the Homepage portrait",()=>{expect(mediaSlots["homepage.heroPortrait"]).toBeDefined();expect(mediaSlots["about.heroPortrait"]).toMatchObject({category:"About",meaningful:true});expect(mediaSlots["spatial.compassPortrait"]).toBeDefined();expect(mediaSlots["spatial.storyBackdropMobile"]).toBeDefined();expect(mediaSlots["realEstate.featuredVideo"]).toBeDefined()})});
