import {mkdir,mkdtemp,writeFile} from "node:fs/promises";
import {tmpdir} from "node:os";
import path from "node:path";
import {describe,expect,it} from "vitest";
import {getProceduralSceneAssets} from "@/lib/media/procedural-assets";
import {deterministicScenePoints,proceduralSceneSchema,proceduralScenes} from "@/lib/media/procedural-scenes";
import {isSafeBackgroundVideoContract,resolveMediaPresentation} from "@/lib/media/presentation";
import {getMediaSlotContract,isMediaAssignmentCompatible} from "@/lib/media/slot-contracts";
import {assignMedia,getAssignedMedia,getDraftAssignedMedia,listAssignments,listDraftAssignments,saveDraftAssignment} from "@/lib/media/assignments";
import {mediaAssetSchema,mediaRoleSchema,type MediaAsset,type MediaPresentation} from "@/lib/media/types";

const now="2026-07-30T00:00:00.000Z";
const presentation:MediaPresentation={mode:"cover",overlayStrength:.35,overlayColor:"#111111",topGradient:0,bottomGradient:0,panelOpacity:0,textShadow:false,focalX:.5,focalY:.5,startPosition:0,endPosition:1,textContrastMode:"automatic",enabled:true,reducedMotionFallback:"static-image"};
function asset(overrides:Partial<MediaAsset>={}):MediaAsset{return mediaAssetSchema.parse({id:"asset",filename:"asset.jpg",originalFilename:"asset.jpg",url:"/asset.jpg",provider:"local",mimeType:"image/jpeg",width:1600,height:1200,fileSize:100,title:{en:"Asset",vi:""},alt:{en:"Asset",vi:""},caption:{en:"",vi:""},focalPoint:{x:.5,y:.5},privacyReviewed:true,rightsStatus:"owner-created",approvedForPublicUse:true,createdAt:now,updatedAt:now,...overrides})}

describe("AC Motion Media System",()=>{
 it("validates the semantic taxonomy and rejects invented roles",()=>{expect(mediaRoleSchema.safeParse("ambient-video").success).toBe(true);expect(mediaRoleSchema.safeParse("compass-portrait").success).toBe(true);expect(mediaRoleSchema.safeParse("magic-luxury-video").success).toBe(false)});
 it("discriminates legacy uploaded images, videos, documents, and procedural scenes",()=>{expect(asset().sourceType).toBe("uploaded-image");expect(asset({mimeType:"video/mp4",url:"/video.mp4"}).sourceType).toBe("uploaded-video");expect(asset({mimeType:"application/pdf",url:"/report.pdf"}).sourceType).toBe("document");expect(getProceduralSceneAssets()[0].sourceType).toBe("procedural-scene")});
 it.each(["diagram","document-reference","compass-portrait"] as const)("keeps %s media contained",mediaRole=>{const resolved=resolveMediaPresentation(asset({mediaRole}),"public",mediaRole==="compass-portrait"?"spatial.compassPortrait":"spatial.compassDiagram",{...presentation,fit:"cover",cropAllowed:true});expect(resolved.fit).toBe("contain");expect(resolved.cropAllowed).toBe(false)});
 it("enforces muted inline looping background video safety",()=>{const resolved=resolveMediaPresentation(asset({mimeType:"video/mp4",url:"/background.mp4",mediaRole:"background-video",decorative:true,videoReadiness:"web-ready"}),"public","homepage.heroVideo",presentation);expect(isSafeBackgroundVideoContract(resolved)).toBe(true);expect(resolved.video.muted).toBe(true);expect(resolved.video.playsInline).toBe(true);expect(resolved.video.reducedMotionFallback).toBe("static-image")});
 it("keeps normal editorial video user-controlled",()=>{const resolved=resolveMediaPresentation(asset({mimeType:"video/webm",url:"/story.webm",mediaRole:"content-video"}),"public",undefined,presentation);expect(resolved.video.autoplay).toBe(false);expect(resolved.video.loop).toBe(false)});
 it("validates every curated scene and generates deterministic geometry",()=>{for(const scene of proceduralScenes)expect(proceduralSceneSchema.safeParse(scene).success).toBe(true);expect(deterministicScenePoints(307,8)).toEqual(deterministicScenePoints(307,8));expect(deterministicScenePoints(307,8)).not.toEqual(deterministicScenePoints(308,8))});
 it("validates Page Asset source compatibility",()=>{const procedure=getProceduralSceneAssets().find(item=>item.sceneId==="spatial-field")!;expect(isMediaAssignmentCompatible(procedure,"spatial.spatialBackdrop")).toBe(true);expect(isMediaAssignmentCompatible(procedure,"spatial.compassPortrait")).toBe(false);expect(getMediaSlotContract("homepage.storyBackdropMobile").backgroundBehavior).toBe("whole-main-page")});
 it("preserves Draft and Published isolation for procedural assignments",async()=>{const root=await mkdtemp(path.join(tmpdir(),"ac-motion-media-")),procedure=getProceduralSceneAssets()[0];await mkdir(path.join(root,".dev-data"),{recursive:true});await writeFile(path.join(root,".dev-data","media-library.json"),JSON.stringify([{...procedure,provider:"procedural"}]),"utf8");await saveDraftAssignment("homepage.ambientScene",procedure.id,presentation,root);expect(await listDraftAssignments(root)).toHaveLength(1);expect(await listAssignments(root)).toHaveLength(0);expect((await getDraftAssignedMedia("homepage.ambientScene",root))?.asset.id).toBe(procedure.id);expect(await getAssignedMedia("homepage.ambientScene",root)).toBeNull()});
 it("rejects incompatible assignment independently from public-use approval",async()=>{const root=await mkdtemp(path.join(tmpdir(),"ac-motion-contract-")),procedure=getProceduralSceneAssets()[0],unapproved=asset({id:"unapproved",approvedForPublicUse:false,privacyReviewed:false});await mkdir(path.join(root,".dev-data"),{recursive:true});await writeFile(path.join(root,".dev-data","media-library.json"),JSON.stringify([{...procedure,provider:"procedural"},unapproved]),"utf8");await expect(saveDraftAssignment("spatial.compassPortrait",procedure.id,presentation,root)).rejects.toThrow(/not compatible/);await expect(assignMedia("homepage.heroPortrait",unapproved.id,presentation,root)).rejects.toThrow(/privacy, rights, and public-use review/);expect(await listAssignments(root)).toHaveLength(0);expect(await listDraftAssignments(root)).toHaveLength(0)});
});
