import {mkdir,readFile,readdir,rename,unlink,writeFile} from "node:fs/promises";
import path from "node:path";
import {contentEntrySchema,type ContentEntry,type ContentLocale,type ContentStatus,type ContentType,type ServiceCategory} from "@/lib/content-studio/types";
import {LocalMediaStorageProvider} from "@/lib/media/storage";
import {listEmbeds} from "@/lib/embeds/storage";

export type ContentQuery={status?:ContentStatus;type?:ContentType;serviceCategory?:ServiceCategory;locale?:ContentLocale;search?:string;contentPillar?:string;targetAudience?:string;funnelStage?:string;strategicObjective?:string;strategySeed?:boolean};
export interface ContentRepository{list(query?:ContentQuery):Promise<ContentEntry[]>;get(id:string):Promise<ContentEntry|null>;findBySlug(slug:string):Promise<ContentEntry|null>;create(input:Omit<ContentEntry,"id"|"createdAt"|"updatedAt"|"publishedAt">):Promise<ContentEntry>;update(id:string,input:Partial<ContentEntry>):Promise<ContentEntry>;delete(id:string):Promise<void>}
export class LocalContentRepository implements ContentRepository{
 constructor(private root=process.cwd()){}private get directory(){return path.join(this.root,".dev-data","content")}
 async list(query:ContentQuery={}){if(process.env.NODE_ENV==="production")return [];let items=await this.readAll();if(query.status)items=items.filter(i=>i.status===query.status);if(query.type)items=items.filter(i=>i.type===query.type);if(query.serviceCategory)items=items.filter(i=>i.serviceCategory===query.serviceCategory);if(query.locale)items=items.filter(i=>!!i.localeContent[query.locale!]);if(query.contentPillar)items=items.filter(i=>i.strategyMetadata?.contentPillar===query.contentPillar);if(query.targetAudience)items=items.filter(i=>i.strategyMetadata?.targetAudience.toLowerCase().includes(query.targetAudience!.toLowerCase()));if(query.funnelStage)items=items.filter(i=>i.strategyMetadata?.funnelStage===query.funnelStage);if(query.strategicObjective)items=items.filter(i=>i.strategyMetadata?.strategicObjective===query.strategicObjective);if(query.strategySeed!==undefined)items=items.filter(i=>i.strategyMetadata?.strategySeed===query.strategySeed);if(query.search){const q=query.search.toLowerCase();items=items.filter(i=>`${i.slug} ${i.localeContent.en?.title||""} ${i.localeContent.vi?.title||""} ${i.tags.join(" ")} ${i.strategyMetadata?.strategicBrief||""}`.toLowerCase().includes(q))}return items.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))}
 async get(id:string){try{return contentEntrySchema.parse(JSON.parse(await readFile(path.join(this.directory,`${id}.json`),"utf8")))}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return null;throw error}}
 async findBySlug(slug:string){return (await this.readAll()).find(i=>i.slug===slug)||null}
 async create(input:Omit<ContentEntry,"id"|"createdAt"|"updatedAt"|"publishedAt">){if(await this.findBySlug(input.slug))throw new Error("Slug is already in use.");const now=new Date().toISOString();const entry=contentEntrySchema.parse({...input,id:crypto.randomUUID(),createdAt:now,updatedAt:now,publishedAt:null});await this.validateReferences(entry);await mkdir(this.directory,{recursive:true});await writeFile(path.join(this.directory,`${entry.id}.json`),JSON.stringify(entry,null,2),{encoding:"utf8",flag:"wx"});return entry}
 async update(id:string,input:Partial<ContentEntry>){const current=await this.get(id);if(!current)throw new Error("Content entry not found.");if(input.slug&&input.slug!==current.slug&&await this.findBySlug(input.slug))throw new Error("Slug is already in use.");const status=input.status||current.status;const entry=contentEntrySchema.parse({...current,...input,id,createdAt:current.createdAt,updatedAt:new Date().toISOString(),publishedAt:status==="published"?(current.publishedAt||new Date().toISOString()):status==="draft"?null:current.publishedAt,publishedLocales:status==="published"?(input.publishedLocales||current.publishedLocales):[]});await this.validateReferences(entry);await this.atomicWrite(entry);return entry}
 async delete(id:string){await unlink(path.join(this.directory,`${id}.json`))}
 private async readAll(){try{const files=(await readdir(this.directory)).filter(f=>f.endsWith(".json"));return Promise.all(files.map(async f=>contentEntrySchema.parse(JSON.parse(await readFile(path.join(this.directory,f),"utf8")))))}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return [];throw error}}
 private async atomicWrite(entry:ContentEntry){await mkdir(this.directory,{recursive:true});const file=path.join(this.directory,`${entry.id}.json`),temp=`${file}.tmp`;await writeFile(temp,JSON.stringify(entry,null,2),"utf8");await rename(temp,file)}
 private async validateReferences(entry:ContentEntry){const assetIds=new Set([entry.featuredImageId,...Object.values(entry.localeContent).flatMap(l=>l?.blocks.flatMap(b=>b.type==="image"?[b.assetId]:b.type==="gallery"?b.assetIds:[])||[])].filter(Boolean));const embedIds=new Set([entry.featuredEmbedId,...Object.values(entry.localeContent).flatMap(l=>l?.blocks.flatMap(b=>b.type==="embed"?[b.embedId]:[])||[])].filter(Boolean));const [assets,embeds]=await Promise.all([new LocalMediaStorageProvider(this.root).list(),listEmbeds(this.root)]);for(const id of assetIds)if(!assets.some(a=>a.id===id))throw new Error(`Referenced media asset not found: ${id}`);for(const id of embedIds)if(!embeds.some(e=>e.id===id))throw new Error(`Referenced embed not found: ${id}`)}
}
export async function publicContent(query:Omit<ContentQuery,"status">={},root=process.cwd()){return (await new LocalContentRepository(root).list({...query,status:"published"})).filter(e=>query.locale?e.publishedLocales.includes(query.locale):e.publishedLocales.length>0)}
export async function relatedContent(entry:ContentEntry,locale:ContentLocale,limit=3,root=process.cwd()){return (await publicContent({locale},root)).filter(i=>i.id!==entry.id).map(i=>({item:i,score:(i.serviceCategory===entry.serviceCategory?4:0)+i.tags.filter(t=>entry.tags.includes(t)).length*2+(i.type===entry.type?1:0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||b.item.updatedAt.localeCompare(a.item.updatedAt)).slice(0,limit).map(x=>x.item)}
export async function contentReferences(kind:"media"|"embed",id:string,root=process.cwd()){return (await new LocalContentRepository(root).list()).filter(e=>e.featuredImageId===id||e.featuredEmbedId===id||Object.values(e.localeContent).some(l=>l?.blocks.some(b=>kind==="media"?(b.type==="image"&&b.assetId===id)||(b.type==="gallery"&&b.assetIds.includes(id)):b.type==="embed"&&b.embedId===id)))}
