import {NextResponse} from "next/server";
import {z} from "zod";
import {LocalContentRepository} from "@/lib/content-studio/repository";
import {contentEntrySchema,contentPillarSchema,contentStatusSchema,contentTypeSchema,funnelStageSchema,localeSchema,serviceCategorySchema,strategicObjectiveSchema} from "@/lib/content-studio/types";
import {getStudioAccess} from "@/lib/media/security";
import type {Capability} from "@/lib/governance/permissions";
export const runtime="nodejs";const repository=new LocalContentRepository();
function denied(capability:Capability){const access=getStudioAccess(undefined,capability);return NextResponse.json({ok:false,error:access.reason},{status:access.actor?403:401})}function fail(error:unknown){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"Content operation failed."},{status:400})}
export async function GET(request:Request){if(!getStudioAccess(undefined,"content.read").enabled)return denied("content.read");const p=new URL(request.url).searchParams,id=p.get("id");if(id)return NextResponse.json({ok:true,entry:await repository.get(id)});try{return NextResponse.json({ok:true,entries:await repository.list({status:contentStatusSchema.optional().parse(p.get("status")||undefined),type:contentTypeSchema.optional().parse(p.get("type")||undefined),serviceCategory:serviceCategorySchema.optional().parse(p.get("service")||undefined),locale:localeSchema.optional().parse(p.get("locale")||undefined),contentPillar:contentPillarSchema.optional().parse(p.get("pillar")||undefined),targetAudience:p.get("audience")||undefined,funnelStage:funnelStageSchema.optional().parse(p.get("funnel")||undefined),strategicObjective:strategicObjectiveSchema.optional().parse(p.get("objective")||undefined),strategySeed:p.has("strategySeed")?p.get("strategySeed")==="true":undefined,search:p.get("search")||undefined})})}catch(error){return fail(error)}}
export async function POST(request:Request){try{const body=contentEntrySchema.omit({id:true,createdAt:true,updatedAt:true,publishedAt:true}).parse(await request.json());const capability:Capability=body.status==="published"?"content.publish":"content.edit";if(!getStudioAccess(undefined,capability).writable)return denied(capability);return NextResponse.json({ok:true,entry:await repository.create(body)},{status:201})}catch(error){return fail(error)}}
export async function PATCH(request:Request){try{const body=z.object({id:z.string(),entry:contentEntrySchema.partial()}).parse(await request.json()),current=await repository.get(body.id);const capability:Capability=body.entry.status==="published"||current?.status==="published"?"content.publish":"content.edit";if(!getStudioAccess(undefined,capability).writable)return denied(capability);return NextResponse.json({ok:true,entry:await repository.update(body.id,body.entry)})}catch(error){return fail(error)}}
export async function DELETE(request:Request){try{const id=new URL(request.url).searchParams.get("id");if(!id)throw new Error("Content ID is required.");const current=await repository.get(id),capability:Capability=current?.status==="published"?"content.publish":"content.edit";if(!getStudioAccess(undefined,capability).writable)return denied(capability);await repository.delete(id);return NextResponse.json({ok:true})}catch(error){return fail(error)}}
