import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import { notFound } from "next/navigation";
import { FAQAccordion, PlaceholderPortrait, ServicePillarCards } from "@/components/cards";
import { ExternalBookingLink, LeadCapture, LeadForm } from "@/components/lead-form";
import { RealEstateHub } from "@/components/real-estate-hub";
import { HomeInspectionHub } from "@/components/home-inspection-hub";
import { SpatialConsultationHub } from "@/components/spatial-consultation-hub";
import { complianceConfig } from "@/data/compliance.config";
import { getPublicServices, getServiceBySlug, isPublicService, type Locale } from "@/data/site.config";
import { isLocale } from "@/lib/i18n";
import { getBookingProvider } from "@/lib/booking-provider";
import {getAssignedMedia,getDraftAssignedMedia} from "@/lib/media/assignments";
import {localizedValue,type MediaSlotKey} from "@/lib/media/types";
import {getAboutMedia} from "@/lib/media/about-media";
import {MotionMediaRenderer} from "@/components/motion-media-renderer";
import {VisualPage} from "@/components/visual-page";
import {SocialLinks} from "@/components/social-links";
import {getPublishedSocialChannels} from "@/lib/social/repository";
import type {SocialChannel} from "@/lib/social/types";

type PageDef={title:string;eyebrow:string;description:string;kind?:"service"|"form"|"legal"|"list"};
const defs:Record<string,PageDef>={
  about:{title:"About Anh Cao",eyebrow:"Personal perspective",description:"A bilingual property educator focused on helping Georgia communities understand transaction context, physical-condition questions, and spatial function."},
  "about-spatial-specialist":{title:"Property intelligence beyond one dimension.",eyebrow:"Spatial Specialist LLC",description:"An umbrella business framework connecting real estate strategy, property context, and spatial function."},
  services:{title:"Property perspectives for clearer decisions.",eyebrow:"Services",description:"Choose real estate strategy or spatial consultation according to your goal.",kind:"list"},
  videos:{title:"Property insight, built for video.",eyebrow:"Media library",description:"Property tours, inspection education, real estate explainers, and spatial observations. Owner videos will appear here after launch.",kind:"list"},
  guides:{title:"Guides for more informed decisions.",eyebrow:"Educational library",description:"Practical, bilingual education across buying, inspection awareness, and spatial function.",kind:"list"},
  reviews:{title:"Client reviews",eyebrow:"Verified experiences",description:"This section will publish only genuine, approved reviews. No reviews are currently configured.",kind:"list"},
  contact:{title:"Tell us what you are evaluating.",eyebrow:"Contact",description:"Start with your goal. Do not include sensitive financial, identity, or private client information.",kind:"form"},
  book:{title:"Choose the conversation you need.",eyebrow:"Book a consultation",description:"Select a service path below. Calendar integration can be connected before launch.",kind:"form"},
  "real-estate":{title:"Real Estate Decisions With More Context",eyebrow:"Anh Cao · Real Estate",description:"Education-led strategy for Georgia buyers, sellers, and investors.",kind:"service"},
  "home-inspection":{title:"Know What You Are Buying Before the House Starts Sending You Invoices.",eyebrow:"Anh Cao · Home Inspection",description:"Calm, technical education about property systems, visible conditions, and informed follow-up.",kind:"service"},
  "spatial-consultation":{title:"Space should work before it tries to impress.",eyebrow:"Anh Cao Spatial Specialist",description:"Feng Shui, space analysis, and property consultation grounded in observable function first.",kind:"service"},
  privacy:{title:"Privacy Policy",eyebrow:"Legal",description:"A launch-ready policy outline that must be reviewed against the final forms, analytics, vendors, and governing requirements.",kind:"legal"},
  terms:{title:"Terms of Use",eyebrow:"Legal",description:"Educational website terms. Final legal review is recommended before public launch.",kind:"legal"},
  accessibility:{title:"Accessibility",eyebrow:"Our commitment",description:"We aim to provide a usable bilingual experience with semantic structure, keyboard access, visible focus, and readable contrast.",kind:"legal"},
};
const serviceChildren:Record<string,string[]>={"real-estate":["buyers","sellers","investors","property-tours","georgia-market","neighborhoods","resources","faq"],"home-inspection":["what-we-inspect","inspection-process","sample-report","standards-ethics","certifications","defect-library","inspection-videos","faq","request-inspection"],"spatial-consultation":["residential-consultation","business-consultation","property-selection","space-audit","methodology","case-studies","videos","faq","book-consultation"]};
const titleCase=(v:string)=>v.split("-").map(w=>w[0]?.toUpperCase()+w.slice(1)).join(" ");
const viTitles:Record<string,string>={about:"Về Anh Cao","about-spatial-specialist":"Trí tuệ tài sản vượt khỏi một chiều nhìn.",services:"Các góc nhìn tài sản cho quyết định rõ ràng hơn.",videos:"Hiểu tài sản qua nội dung video.",guides:"Cẩm nang cho quyết định sáng suốt hơn.",reviews:"Đánh giá khách hàng","contact":"Hãy cho chúng tôi biết Anh/Chị đang đánh giá điều gì.",book:"Chọn cuộc trao đổi Anh/Chị cần.","real-estate":"Quyết định bất động sản với nhiều bối cảnh hơn","home-inspection":"Hiểu căn nhà trước khi nó bắt đầu gửi hóa đơn sửa chữa.","spatial-consultation":"Không gian nên vận hành tốt trước khi gây ấn tượng.",privacy:"Chính sách bảo mật",terms:"Điều khoản sử dụng",accessibility:"Khả năng tiếp cận",buyers:"Người mua nhà",sellers:"Người bán nhà",investors:"Nhà đầu tư","request-inspection":"Yêu cầu kiểm tra nhà","book-consultation":"Đặt lịch tư vấn không gian"};

export async function generateMetadata({params}:{params:Promise<{locale:string;slug:string[]}>}):Promise<Metadata>{const {locale,slug}=await params;const key=slug.join("/");const def=defs[key]||defs[slug[0]];const service=getServiceBySlug(slug[0]);return {title:def?.title||titleCase(slug.at(-1)||"Page"),description:def?.description,alternates:{canonical:`/${locale}/${key}`,languages:{en:`/en/${key}`,vi:`/vi/${key}`}},robots:service&&!isPublicService(service)?{index:false,follow:false}:undefined}}

export default async function ContentPage({params,searchParams}:{params:Promise<{locale:string;slug:string[]}>;searchParams:Promise<Record<string,string|string[]|undefined>>}) {const [{locale:raw,slug},query]=await Promise.all([params,searchParams]);if(!isLocale(raw))notFound();const locale:Locale=raw;const vi=locale==="vi";const key=slug.join("/");const root=slug[0];const child=slug[1];
  const visualPreview=query.visualPreview==="1";
  const hiddenService=getServiceBySlug(root);
  const developmentPreview=process.env.NODE_ENV==="development"&&(visualPreview||query.mediaPreview==="1");
  if(hiddenService&&!isPublicService(hiddenService)&&!developmentPreview)notFound();
  if(key==="real-estate")return <VisualPage page="deal" locale={locale} preview={visualPreview}><RealEstateHub locale={locale}/></VisualPage>;
  if(key==="home-inspection")return <VisualPage page="condition" locale={locale} preview={visualPreview}><HomeInspectionHub locale={locale}/></VisualPage>;
  if(key==="spatial-consultation"){const slots=["spatial.heroPortrait","spatial.heroImage","spatial.compassPortrait","spatial.compassDiagram","spatial.orientationVisual","spatial.educationMedia","spatial.sectionBackground","spatial.featuredVideo"] as MediaSlotKey[];const publicMedia=Object.fromEntries(await Promise.all(slots.map(async slot=>[slot,(await getAssignedMedia(slot))?.asset||null])));const draftPreview=query.mediaPreview==="1"&&process.env.NODE_ENV!=="production";const drafts=draftPreview?Object.fromEntries(await Promise.all(slots.map(async slot=>[slot,(await getDraftAssignedMedia(slot))?.asset||null]))):{};return <VisualPage page="space" locale={locale} preview={visualPreview}><SpatialConsultationHub locale={locale} media={{...publicMedia,...Object.fromEntries(Object.entries(drafts).filter(([,asset])=>asset))}} draftPreview={draftPreview}/></VisualPage>}
  if(key==="book"||key==="contact"){const socialChannels=key==="contact"?await getPublishedSocialChannels("contact"):[];return <VisualPage page={key==="contact"?"contact":"booking"} locale={locale} preview={visualPreview}><ConversionPage locale={locale} contact={key==="contact"} initialService={typeof query.service==="string"?query.service:null} socialChannels={socialChannels}/></VisualPage>}
  const base=defs[key]||defs[root]; if(!base&&!serviceChildren[root]?.includes(child))notFound(); const englishTitle=child?titleCase(child):base.title;const title=vi?(viTitles[key]||viTitles[child]||englishTitle):englishTitle;const description=child?(vi?`Thông tin giáo dục về ${title.toLowerCase()}, được thiết kế để mở rộng bằng nội dung đã xác minh.`:`Educational guidance for ${title.toLowerCase()}, ready to expand with verified owner content.`):base.description;const isForm=base.kind==="form"||["buyers","sellers","request-inspection","book-consultation"].includes(child);
  const aboutDraft=key==="about"&&query.mediaPreview==="1"&&process.env.NODE_ENV!=="production"?await getDraftAssignedMedia("about.heroPortrait"):null;
  const aboutMedia=key==="about"?(aboutDraft??await getAboutMedia()):null;
  const content=<><section className={`inner-hero ${root}`} data-visual-section={key==="about"?"hero":undefined}><div><p className="eyebrow">{base.eyebrow}</p><h1>{title}</h1><p>{description}</p>{base.kind==="service"&&!child&&<Link className="button button-accent" href={`/${locale}/${root}/${root==="real-estate"?"buyers":root==="home-inspection"?"request-inspection":"book-consultation"}`}>{vi?"Bắt đầu":"Get started"}<ArrowRight/></Link>}</div>{key==="about"&&(aboutMedia?<figure className="about-portrait-frame">{aboutDraft&&<span className="development-preview-label">DRAFT MEDIA PREVIEW</span>}<MotionMediaRenderer asset={aboutMedia.asset} context="public" slot="about.heroPortrait" presentation={aboutMedia.assignment.presentation} alt={localizedValue(aboutMedia.asset.alt,locale)} fill priority sizes="(max-width: 700px) 100vw, 28vw"/></figure>:<PlaceholderPortrait/>)}</section>
  {key==="services"&&<section className="section services-perspectives" data-visual-section="services"><div className="services-perspectives-intro"><p className="eyebrow">{vi?"Hai góc nhìn đang hoạt động":"Two active perspectives"}</p><h2>{vi?"Cùng một tài sản. Hai cách đặt câu hỏi.":"One property. Two ways to ask better questions."}</h2><p>{vi?"Chọn DEAL cho bối cảnh giao dịch và thị trường. Chọn SPACE cho bố cục, định hướng và cách không gian vận hành.":"Choose DEAL for transaction and market context. Choose SPACE for layout, orientation, and how the environment works."}</p></div><ServicePillarCards locale={locale}/></section>}
  {key==="about-spatial-specialist"&&<Framework locale={locale}/>} {key==="about"&&<About locale={locale}/>} 
  {base.kind==="service"&&!child&&<ServiceOverview locale={locale} root={root}/>} 
  {base.kind==="list"&&key==="videos"&&<EmptyMedia locale={locale}/>} {key==="reviews"&&<EmptyMedia locale={locale} reviews/>}
  {isForm&&<section className="form-section"><div><p className="eyebrow">{vi?"Bước tiếp theo":"Next step"}</p><h2>{vi?"Chia sẻ mục tiêu, không cần gửi dữ liệu nhạy cảm.":"Share the goal, not sensitive data."}</h2><p>{vi?"Biểu mẫu đang dùng adapter mock để website build được mà chưa cần dịch vụ trả phí.":"The form uses a mock adapter until a launch provider is connected."}</p></div><LeadForm locale={locale} type={root==="real-estate"?(child==="sellers"?"seller":"buyer"):root==="home-inspection"?"inspection":root==="spatial-consultation"?"spatial-residential":"general"}/></section>}
  {child&&!isForm&&<GenericDetail locale={locale} root={root}/>} {base.kind==="legal"&&<LegalBody locale={locale} page={key}/>} {key==="contact"&&null}
  </>;return key==="about"?<VisualPage page="about" locale={locale} preview={visualPreview}>{content}</VisualPage>:key==="services"?<VisualPage page="services" locale={locale} preview={visualPreview}>{content}</VisualPage>:content}

function ServiceOverview({locale,root}:{locale:Locale;root:string}){const vi=locale==="vi";const children=serviceChildren[root]||[];return <><section className="section split"><div><p className="eyebrow">{vi?"Dịch vụ độc lập":"Independent service"}</p><h2>{vi?"Chọn đúng mức hỗ trợ cho quyết định hiện tại.":"Choose the right depth for the decision in front of you."}</h2></div><p>{root==="spatial-consultation"?complianceConfig.notices.spatial:root==="home-inspection"?complianceConfig.notices.inspection:complianceConfig.notices.realEstate}</p></section><section className="link-grid">{children.map(c=><Link key={c} href={`/${locale}/${root}/${c}`}><span>{titleCase(c)}</span><ArrowRight/></Link>)}</section></>}
function Framework({locale}:{locale:Locale}){const vi=locale==="vi";return <section className="section"><div className="section-heading"><p className="eyebrow">The Property Intelligence Framework</p><h2>{vi?"Tìm · Đánh giá · Hiểu · Cải thiện":"Find · Evaluate · Understand · Improve"}</h2></div><div className="steps">{["Find","Evaluate","Understand","Improve"].map((s,i)=><div key={s}><span>0{i+1}</span><h3>{s}</h3><p>{vi?"Một giai đoạn rõ ràng trong hành trình hiểu tài sản.":"A distinct stage in building a clearer property decision."}</p></div>)}</div></section>}
function About({locale}:{locale:Locale}){const vi=locale==="vi";const lenses=vi?[["01","Con người","Giao tiếp song ngữ và bối cảnh của từng quyết định."],["02","Góc nhìn","Kết nối thị trường, tài sản và cách không gian được sử dụng."],["03","Hệ thống","Tách rõ dữ kiện quan sát, bối cảnh và lớp diễn giải tùy chọn."]]:[["01","Person","Bilingual communication grounded in the context of each decision."],["02","Perspective","Connecting market context, property, and the way a space is used."],["03","System","Separating observable facts, practical context, and optional interpretation."]];return <section className="about-perspective" data-visual-section="perspective"><div className="about-perspective-lead"><p className="eyebrow">{vi?"Con người · Góc nhìn · Hệ thống":"Person · Perspective · System"}</p><h2>{vi?"Nhìn tài sản như một hệ thống các mối quan hệ.":"See property as a system of relationships."}</h2><p>{vi?"Cách tiếp cận của Anh Cao bắt đầu bằng những câu hỏi rõ ràng: quyết định nào đang được cân nhắc, bối cảnh nào quan trọng và không gian cần hỗ trợ con người như thế nào.":"Anh Cao’s approach begins with clear questions: what decision is being considered, which context matters, and how the environment needs to support the people inside it."}</p></div><ol>{lenses.map(([index,title,copy])=><li key={index}><span>{index}</span><h3>{title}</h3><p>{copy}</p></li>)}</ol></section>}
function GenericDetail({locale,root}:{locale:Locale;root:string}){const vi=locale==="vi";return <section className="section content-detail"><div className="content-block"><h2>{vi?"Anh/Chị sẽ tìm thấy gì ở đây":"What this page will help you understand"}</h2><ul><li><Check/> {vi?"Dữ kiện và quan sát thực tế":"Observable facts and practical context"}</li><li><Check/> {vi?"Các câu hỏi cần đặt ra":"Questions worth asking"}</li><li><Check/> {vi?"Khi nào nên tìm chuyên gia phù hợp":"When to involve an appropriate specialist"}</li></ul></div><FAQAccordion items={[{q:vi?"Dịch vụ này có bắt buộc dùng cùng dịch vụ khác không?":"Must this service be used with another service?",a:vi?"Không. Mỗi dịch vụ độc lập và có thể được lựa chọn riêng.":"No. Every service is independent and may be selected on its own."},{q:vi?"Nội dung này có thay thế tư vấn chuyên môn không?":"Does this content replace professional advice?",a:root==="spatial-consultation"?complianceConfig.notices.spatial:root==="home-inspection"?complianceConfig.notices.inspection:complianceConfig.notices.realEstate}]}/><Link className="button button-dark" href={`/${locale}/book`}>{vi?"Đặt cuộc trao đổi":"Book a conversation"}<ArrowRight/></Link></section>}
function EmptyMedia({locale,reviews=false}:{locale:Locale;reviews?:boolean}){return <section className="empty-state"><span>{reviews?"00":"▶"}</span><h2>{locale==="vi"?(reviews?"Chưa có review đã xác minh":"Video của Anh Cao sẽ xuất hiện tại đây"):(reviews?"No verified reviews yet":"Anh Cao’s videos will live here")}</h2><p>{locale==="vi"?"Khu vực này tự động ẩn nội dung chưa được cung cấp hoặc xác minh.":"This area intentionally hides content that has not been supplied or verified."}</p></section>}
function LegalBody({locale,page}:{locale:Locale;page:string}){return <section className="section prose"><h2>{locale==="vi"?"Bản dự thảo trước khi ra mắt":"Pre-launch policy outline"}</h2><p>{page==="privacy"?"Forms collect only the information a visitor voluntarily provides. Final retention, analytics, cookie, and vendor details must be added after launch providers are chosen.":page==="terms"?"Site content is educational and does not create a professional-client relationship. Service availability and regulated claims depend on approved credentials and agreements.":"If you encounter an accessibility barrier, contact information will be published here when the owner supplies it. We will work to provide the content in an accessible format."}</p></section>}

function ConversionPage({locale,contact,initialService,socialChannels=[]}:{locale:Locale;contact:boolean;initialService:string|null;socialChannels?:SocialChannel[]}){const vi=locale==="vi";const booking=getBookingProvider();const services=getPublicServices();return <div className={`conversion-page ${contact?"contact-conversion":"book-conversion"}`}><section className="conversion-hero"><div><p className="eyebrow">{contact?(vi?"Liên hệ":"Contact"):(vi?"Đặt lịch & yêu cầu dịch vụ":"Booking & service inquiry")}</p><h1>{contact?(vi?"Bắt đầu bằng điều Anh/Chị đang cần làm rõ.":"Start with what you need to clarify."):(vi?"Chọn đúng cuộc trao đổi cho quyết định tiếp theo.":"Choose the right conversation for your next decision.")}</h1><p>{vi?"Chỉ cung cấp thông tin cần thiết. Không gửi dữ liệu tài chính, định danh hoặc tài liệu nhạy cảm.":"Share only what is needed. Do not include sensitive financial, identity, or private documents."}</p>{booking&&!contact&&<ExternalBookingLink url={booking.url} locale={locale}/>}</div><aside data-service-count={services.length}>{services.map(service=><span key={service.key}>{service.lens}</span>)}</aside></section><section className="conversion-workspace"><LeadCapture locale={locale} initialService={initialService} contact={contact}/></section>{contact&&socialChannels.length>0&&<section className="contact-social-system"><div><p className="eyebrow">{vi?"Kênh chính thức":"Official channels"}</p><h2>{vi?"Theo dõi nội dung của Anh Cao":"Follow Anh Cao's work"}</h2><p>{vi?"Các liên kết này được quản lý và xuất bản trực tiếp từ AC Studio.":"These destinations are governed and published directly from AC Studio."}</p></div><SocialLinks channels={socialChannels} locale={locale} variant="contact"/></section>}</div>}
