import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import { notFound } from "next/navigation";
import { ArticleCard, FAQAccordion, PlaceholderPortrait, ServicePillarCards } from "@/components/cards";
import { LeadForm } from "@/components/lead-form";
import { RealEstateHub } from "@/components/real-estate-hub";
import { HomeInspectionHub } from "@/components/home-inspection-hub";
import { complianceConfig } from "@/data/compliance.config";
import type { Locale } from "@/data/site.config";
import { contentForLocale } from "@/lib/content";
import { isLocale } from "@/lib/i18n";

type PageDef={title:string;eyebrow:string;description:string;kind?:"service"|"form"|"legal"|"list"};
const defs:Record<string,PageDef>={
  about:{title:"About Anh Cao",eyebrow:"Personal perspective",description:"A bilingual property educator focused on helping Georgia communities understand transactions, physical condition, and spatial function."},
  "about-spatial-specialist":{title:"Property intelligence beyond one dimension.",eyebrow:"Spatial Specialist LLC",description:"An umbrella business framework that examines property through transaction, condition, and space."},
  services:{title:"Three independent ways to understand property.",eyebrow:"Services",description:"Choose real estate strategy, home inspection education, or spatial consultation according to your goal.",kind:"list"},
  videos:{title:"Property insight, built for video.",eyebrow:"Media library",description:"Property tours, inspection education, real estate explainers, and spatial observations. Owner videos will appear here after launch.",kind:"list"},
  guides:{title:"Guides for more informed decisions.",eyebrow:"Educational library",description:"Practical, bilingual education across buying, inspection awareness, and spatial function.",kind:"list"},
  reviews:{title:"Client reviews",eyebrow:"Verified experiences",description:"This section will publish only genuine, approved reviews. No reviews are currently configured.",kind:"list"},
  contact:{title:"Tell us what you are evaluating.",eyebrow:"Contact",description:"Start with your goal. Do not include sensitive financial, identity, or private client information.",kind:"form"},
  book:{title:"Choose the conversation you need.",eyebrow:"Book a consultation",description:"Select a service path below. Calendar integration can be connected before launch.",kind:"form"},
  "real-estate":{title:"Real Estate Decisions With More Context",eyebrow:"Anh Cao · Real Estate",description:"Education-led strategy for Georgia buyers, sellers, and investors.",kind:"service"},
  "home-inspection":{title:"Know What You Are Buying Before the House Starts Sending You Invoices.",eyebrow:"Anh Cao · Home Inspection",description:"Calm, technical education about property systems, visible conditions, and informed follow-up.",kind:"service"},
  "spatial-consultation":{title:"Space should work before it tries to impress.",eyebrow:"Anh Cao Spatial Specialist",description:"Feng Shui, space analysis, and property consultation grounded in observable function first.",kind:"service"},
  privacy:{title:"Privacy Policy",eyebrow:"Legal",description:"A launch-ready policy outline that must be reviewed against the final forms, analytics, vendors, and governing requirements.",kind:"legal"},
  terms:{title:"Terms of Use",eyebrow:"Legal",description:"Educational website terms. Final legal review is recommended before public launch.",kind:"legal"},
  accessibility:{title:"Accessibility",eyebrow:"Our commitment",description:"We aim to provide a usable bilingual experience with semantic structure, keyboard access, visible focus, and readable contrast.",kind:"legal"},
};
const serviceChildren:Record<string,string[]>={"real-estate":["buyers","sellers","investors","property-tours","georgia-market","neighborhoods","resources","faq"],"home-inspection":["what-we-inspect","inspection-process","sample-report","standards-ethics","certifications","defect-library","inspection-videos","faq","request-inspection"],"spatial-consultation":["residential-consultation","business-consultation","property-selection","space-audit","methodology","case-studies","videos","faq","book-consultation"]};
const titleCase=(v:string)=>v.split("-").map(w=>w[0]?.toUpperCase()+w.slice(1)).join(" ");
const viTitles:Record<string,string>={about:"Về Anh Cao","about-spatial-specialist":"Trí tuệ tài sản vượt khỏi một chiều nhìn.",services:"Ba cách độc lập để hiểu một tài sản.",videos:"Hiểu tài sản qua nội dung video.",guides:"Cẩm nang cho quyết định sáng suốt hơn.",reviews:"Đánh giá khách hàng","contact":"Hãy cho chúng tôi biết Anh/Chị đang đánh giá điều gì.",book:"Chọn cuộc trao đổi Anh/Chị cần.","real-estate":"Quyết định bất động sản với nhiều bối cảnh hơn","home-inspection":"Hiểu căn nhà trước khi nó bắt đầu gửi hóa đơn sửa chữa.","spatial-consultation":"Không gian nên vận hành tốt trước khi gây ấn tượng.",privacy:"Chính sách bảo mật",terms:"Điều khoản sử dụng",accessibility:"Khả năng tiếp cận",buyers:"Người mua nhà",sellers:"Người bán nhà",investors:"Nhà đầu tư","request-inspection":"Yêu cầu kiểm tra nhà","book-consultation":"Đặt lịch tư vấn không gian"};

export async function generateMetadata({params}:{params:Promise<{locale:string;slug:string[]}>}):Promise<Metadata>{const {locale,slug}=await params;const key=slug.join("/");const def=defs[key]||defs[slug[0]];return {title:def?.title||titleCase(slug.at(-1)||"Page"),description:def?.description,alternates:{canonical:`/${locale}/${key}`,languages:{en:`/en/${key}`,vi:`/vi/${key}`}}}}

export default async function ContentPage({params}:{params:Promise<{locale:string;slug:string[]}>}) {const {locale:raw,slug}=await params;if(!isLocale(raw))notFound();const locale:Locale=raw;const vi=locale==="vi";const key=slug.join("/");const root=slug[0];const child=slug[1];const guides=contentForLocale(locale);const guide=slug[0]==="guides"&&slug[1]?guides.find(g=>g.slug===slug[1]):null;if(guide)return <article className="article-page"><p className="eyebrow">{guide.categories[0]} · DEMO CONTENT</p><h1>{guide.title}</h1><p className="article-dek">{guide.description}</p><div className="article-meta">{guide.author} · {guide.publishedAt}</div><div className="article-body">{guide.body.map(p=><p key={p}>{p}</p>)}</div><div className="compliance-notice">{complianceConfig.notices[guide.serviceLine==="real-estate"?"realEstate":guide.serviceLine==="home-inspection"?"inspection":"spatial"]}</div><Link className="button button-dark" href={guide.cta.href}>{guide.cta.label}<ArrowRight/></Link></article>;
  if(key==="real-estate")return <RealEstateHub locale={locale}/>;
  if(key==="home-inspection")return <HomeInspectionHub locale={locale}/>;
  const base=defs[key]||defs[root]; if(!base&&!serviceChildren[root]?.includes(child))notFound(); const englishTitle=child?titleCase(child):base.title;const title=vi?(viTitles[key]||viTitles[child]||englishTitle):englishTitle;const description=child?(vi?`Thông tin giáo dục về ${title.toLowerCase()}, được thiết kế để mở rộng bằng nội dung đã xác minh.`:`Educational guidance for ${title.toLowerCase()}, ready to expand with verified owner content.`):base.description;const isForm=base.kind==="form"||["buyers","sellers","request-inspection","book-consultation"].includes(child);
  return <><section className={`inner-hero ${root}`}><div><p className="eyebrow">{base.eyebrow}</p><h1>{title}</h1><p>{description}</p>{base.kind==="service"&&!child&&<Link className="button button-accent" href={`/${locale}/${root}/${root==="real-estate"?"buyers":root==="home-inspection"?"request-inspection":"book-consultation"}`}>{vi?"Bắt đầu":"Get started"}<ArrowRight/></Link>}</div>{key==="about"&&<PlaceholderPortrait/>}</section>
  {key==="services"&&<section className="section"><ServicePillarCards locale={locale}/></section>}
  {key==="about-spatial-specialist"&&<Framework locale={locale}/>} {key==="about"&&<About locale={locale}/>} 
  {base.kind==="service"&&!child&&<ServiceOverview locale={locale} root={root}/>} 
  {base.kind==="list"&&key==="guides"&&<section className="section"><div className="article-grid">{guides.map(g=><ArticleCard key={g.slug} item={g} locale={locale}/>)}</div></section>}
  {base.kind==="list"&&key==="videos"&&<EmptyMedia locale={locale}/>} {key==="reviews"&&<EmptyMedia locale={locale} reviews/>}
  {isForm&&<section className="form-section"><div><p className="eyebrow">{vi?"Bước tiếp theo":"Next step"}</p><h2>{vi?"Chia sẻ mục tiêu, không cần gửi dữ liệu nhạy cảm.":"Share the goal, not sensitive data."}</h2><p>{vi?"Biểu mẫu đang dùng adapter mock để website build được mà chưa cần dịch vụ trả phí.":"The form uses a mock adapter until a launch provider is connected."}</p></div><LeadForm locale={locale} type={root==="real-estate"?(child==="sellers"?"seller":"buyer"):root==="home-inspection"?"inspection":root==="spatial-consultation"?"spatial-consultation":"general"}/></section>}
  {child&&!isForm&&<GenericDetail locale={locale} root={root}/>} {base.kind==="legal"&&<LegalBody locale={locale} page={key}/>} {key==="book"&&<BookingSelector locale={locale}/>} {key==="contact"&&null}
  </>}

function ServiceOverview({locale,root}:{locale:Locale;root:string}){const vi=locale==="vi";const children=serviceChildren[root]||[];return <><section className="section split"><div><p className="eyebrow">{vi?"Dịch vụ độc lập":"Independent service"}</p><h2>{vi?"Chọn đúng mức hỗ trợ cho quyết định hiện tại.":"Choose the right depth for the decision in front of you."}</h2></div><p>{root==="spatial-consultation"?complianceConfig.notices.spatial:root==="home-inspection"?complianceConfig.notices.inspection:complianceConfig.notices.realEstate}</p></section><section className="link-grid">{children.map(c=><Link key={c} href={`/${locale}/${root}/${c}`}><span>{titleCase(c)}</span><ArrowRight/></Link>)}</section></>}
function Framework({locale}:{locale:Locale}){const vi=locale==="vi";return <section className="section"><div className="section-heading"><p className="eyebrow">The Property Intelligence Framework</p><h2>{vi?"Tìm · Đánh giá · Hiểu · Cải thiện":"Find · Evaluate · Understand · Improve"}</h2></div><div className="steps">{["Find","Evaluate","Understand","Improve"].map((s,i)=><div key={s}><span>0{i+1}</span><h3>{s}</h3><p>{vi?"Một giai đoạn rõ ràng trong hành trình hiểu tài sản.":"A distinct stage in building a clearer property decision."}</p></div>)}</div></section>}
function About({locale}:{locale:Locale}){return <section className="section prose"><h2>{locale==="vi"?"Câu chuyện đang chờ Anh Cao xác nhận":"A story waiting for owner approval"}</h2><p>{locale==="vi"?"Trang này cố ý không bịa tiểu sử, lịch sử giao dịch hoặc chức danh chưa được xác minh. Khung nội dung tập trung vào góc nhìn Việt-Mỹ, giáo dục khách hàng và giao tiếp song ngữ.":"This page intentionally avoids inventing biography, transactions, or unverified professional titles. Its approved structure centers a Vietnamese-American perspective, client education, and bilingual communication."}</p></section>}
function GenericDetail({locale,root}:{locale:Locale;root:string}){const vi=locale==="vi";return <section className="section content-detail"><div className="content-block"><h2>{vi?"Anh/Chị sẽ tìm thấy gì ở đây":"What this page will help you understand"}</h2><ul><li><Check/> {vi?"Dữ kiện và quan sát thực tế":"Observable facts and practical context"}</li><li><Check/> {vi?"Các câu hỏi cần đặt ra":"Questions worth asking"}</li><li><Check/> {vi?"Khi nào nên tìm chuyên gia phù hợp":"When to involve an appropriate specialist"}</li></ul></div><FAQAccordion items={[{q:vi?"Dịch vụ này có bắt buộc dùng cùng dịch vụ khác không?":"Must this service be used with another service?",a:vi?"Không. Mỗi dịch vụ độc lập và có thể được lựa chọn riêng.":"No. Every service is independent and may be selected on its own."},{q:vi?"Nội dung này có thay thế tư vấn chuyên môn không?":"Does this content replace professional advice?",a:root==="spatial-consultation"?complianceConfig.notices.spatial:root==="home-inspection"?complianceConfig.notices.inspection:complianceConfig.notices.realEstate}]}/><Link className="button button-dark" href={`/${locale}/book`}>{vi?"Đặt cuộc trao đổi":"Book a conversation"}<ArrowRight/></Link></section>}
function EmptyMedia({locale,reviews=false}:{locale:Locale;reviews?:boolean}){return <section className="empty-state"><span>{reviews?"00":"▶"}</span><h2>{locale==="vi"?(reviews?"Chưa có review đã xác minh":"Video của Anh Cao sẽ xuất hiện tại đây"):(reviews?"No verified reviews yet":"Anh Cao’s videos will live here")}</h2><p>{locale==="vi"?"Khu vực này tự động ẩn nội dung chưa được cung cấp hoặc xác minh.":"This area intentionally hides content that has not been supplied or verified."}</p></section>}
function BookingSelector({locale}:{locale:Locale}){const items=[["Real Estate","real-estate/buyers"],["Home Inspection","home-inspection/request-inspection"],["Report Review","home-inspection/sample-report"],["Spatial Consultation","spatial-consultation/book-consultation"]];return <section className="booking-grid">{items.map(([l,h])=><Link href={`/${locale}/${h}`} key={l}><span>{l}</span><ArrowRight/></Link>)}</section>}
function LegalBody({locale,page}:{locale:Locale;page:string}){return <section className="section prose"><h2>{locale==="vi"?"Bản dự thảo trước khi ra mắt":"Pre-launch policy outline"}</h2><p>{page==="privacy"?"Forms collect only the information a visitor voluntarily provides. Final retention, analytics, cookie, and vendor details must be added after launch providers are chosen.":page==="terms"?"Site content is educational and does not create a professional-client relationship. Service availability and regulated claims depend on approved credentials and agreements.":"If you encounter an accessibility barrier, contact information will be published here when the owner supplies it. We will work to provide the content in an accessible format."}</p></section>}
