"use client";
import { useState } from "react";
import type { CatalogItem, CatalogItemType } from "@/lib/catalog/types";

const emptyLocale = () => ({ title: "", shortDescription: "", description: "", seoTitle: "", seoDescription: "" });
function newDraft(type: CatalogItemType): CatalogItem { const timestamp = new Date().toISOString(); return { id: crypto.randomUUID(), slug: "", status: "draft", type, availability: "coming-soon", localeContent: { en: emptyLocale() }, publishedLocales: [], priceMinor: null, currency: "USD", mediaIds: [], category: "", tags: [], featured: false, ...(type === "physical" ? { physical: { sku: "", inventoryPolicy: "track" as const, shippingClass: "", variants: [], podProviderRef: null } } : {}), ...(type === "digital" ? { digital: { assetId: null, deliveryPolicy: "entitlement" as const, previewEmbedId: null, formatLabel: "" } } : {}), ...(type === "service" ? { service: { pillar: "general" as const, pricingModel: "quote-required" as const, bookingServiceKey: "", durationMinutes: null } } : {}), ...(type === "affiliate" ? { affiliate: { merchant: "", url: "https://", disclosure: "" } } : {}), createdAt: timestamp, updatedAt: timestamp, publishedAt: null }; }
export function CatalogStudioClient({ initialItems }: { initialItems: CatalogItem[] }) { const [items, setItems] = useState(initialItems); const [draft, setDraft] = useState<CatalogItem | null>(null); const [status, setStatus] = useState(""); async function save(nextStatus: CatalogItem["status"]) { if (!draft) return; const response = await fetch("/api/studio/catalog", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ item: { ...draft, status: nextStatus, publishedLocales: nextStatus === "active" ? Object.keys(draft.localeContent) : [] } }) }); const result = await response.json(); setStatus(result.ok ? `Catalog item saved as ${nextStatus}.` : result.error); if (result.ok) { setDraft(result.item); setItems((records) => [...records.filter((item) => item.id !== result.item.id), result.item]); } }
  if (draft) { const en = draft.localeContent.en ?? emptyLocale(); return <section className="catalog-editor"><header><div><button className="studio-secondary" onClick={() => setDraft(null)}>← Catalog</button><p className="eyebrow">{draft.type} editor</p><h1>{en.title || "Untitled draft"}</h1></div><div><button onClick={() => void save("draft")}>Save Draft</button><button onClick={() => void save("active")}>Activate</button></div></header><div className="catalog-editor-grid"><label>Title<input value={en.title} onChange={(event) => setDraft({ ...draft, localeContent: { ...draft.localeContent, en: { ...en, title: event.target.value } } })}/></label><label>Slug<input value={draft.slug} onChange={(event) => setDraft({ ...draft, slug: event.target.value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") })}/></label><label>Short description<textarea value={en.shortDescription} onChange={(event) => setDraft({ ...draft, localeContent: { ...draft.localeContent, en: { ...en, shortDescription: event.target.value } } })}/></label><label>Availability<select value={draft.availability} onChange={(event) => setDraft({ ...draft, availability: event.target.value as CatalogItem["availability"] })}><option>coming-soon</option><option>available</option><option>quote-required</option><option>unavailable</option></select></label><label>Price in cents<input type="number" min="0" value={draft.priceMinor ?? ""} onChange={(event) => setDraft({ ...draft, priceMinor: event.target.value ? Number(event.target.value) : null })}/></label>{draft.type === "affiliate" && draft.affiliate && <><label>Merchant<input value={draft.affiliate.merchant} onChange={(event) => setDraft({ ...draft, affiliate: { ...draft.affiliate!, merchant: event.target.value } })}/></label><label>HTTPS affiliate URL<input value={draft.affiliate.url} onChange={(event) => setDraft({ ...draft, affiliate: { ...draft.affiliate!, url: event.target.value } })}/></label></>}</div><output className="studio-status">{status}</output></section>; }
  return <section className="content-list"><header><div><p className="eyebrow">Catalog workstation</p><h1>Catalog</h1><p>Physical, digital, service, and affiliate records share one typed source of truth.</p></div><div className="catalog-create-actions">{(["physical", "digital", "service", "affiliate"] as const).map((type) => <button key={type} onClick={() => setDraft(newDraft(type))}>New {type}</button>)}</div></header><div className="content-rows">{items.map((item) => <article key={item.id}><div><small>{item.type} · {item.availability}</small><strong>{item.localeContent.en?.title ?? item.localeContent.vi?.title}</strong><span>{item.status} · {item.slug}</span></div><button onClick={() => setDraft(item)}>Edit</button></article>)}{items.length === 0 && <div className="studio-empty"><h2>No catalog records.</h2><p>Create a Draft when real product or service information is ready. Nothing is seeded publicly.</p></div>}</div></section>; }

