"use client";
import {useState} from "react";
import {Clipboard,Link2,Trash2} from "lucide-react";
import {EmbedRenderer} from "@/components/embed-renderer";
import {embedSlots,type EmbedAssignment,type EmbedBlock,type EmbedSlotKey} from "@/lib/embeds/types";

type Draft={url:string;titleEn:string;titleVi:string;captionEn:string;captionVi:string;aspectRatio:EmbedBlock["aspectRatio"];theme:EmbedBlock["theme"];allowedPermissions:EmbedBlock["allowedPermissions"]};
const empty:Draft={url:"",titleEn:"",titleVi:"",captionEn:"",captionVi:"",aspectRatio:"16:9",theme:"auto",allowedPermissions:[]};
export function EmbedStudio({initialEmbeds,initialAssignments,onStatus}:{initialEmbeds:EmbedBlock[];initialAssignments:EmbedAssignment[];onStatus:(value:string)=>void}){
 const [embeds,setEmbeds]=useState(initialEmbeds),[assignments,setAssignments]=useState(initialAssignments),[draft,setDraft]=useState(empty),[preview,setPreview]=useState<EmbedBlock|null>(null),[editing,setEditing]=useState<string|null>(null);
 const input=()=>({url:draft.url,title:{en:draft.titleEn,vi:draft.titleVi},caption:{en:draft.captionEn,vi:draft.captionVi},aspectRatio:draft.aspectRatio,theme:draft.theme,autoplay:false,allowedPermissions:draft.allowedPermissions});
 async function refresh(){const [a,b]=await Promise.all([fetch("/api/studio/embeds").then(r=>r.json()),fetch("/api/studio/embed-assignments").then(r=>r.json())]);if(a.ok)setEmbeds(a.embeds);if(b.ok)setAssignments(b.assignments)}
 async function inspect(e:React.FormEvent){e.preventDefault();const result=await fetch("/api/studio/embeds",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(input())}).then(r=>r.json());setPreview(result.ok?result.embed:null);onStatus(result.ok?"Safe preview ready. Review it before saving.":result.error)}
 async function save(){const result=await fetch("/api/studio/embeds",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({id:editing||undefined,input:input()})}).then(r=>r.json());onStatus(result.ok?(editing?"Embed updated.":"Embed saved."):result.error);if(result.ok){setDraft(empty);setPreview(null);setEditing(null);await refresh()}}
 function edit(item:EmbedBlock){setEditing(item.id);setDraft({url:item.sourceUrl,titleEn:item.title.en,titleVi:item.title.vi,captionEn:item.caption.en,captionVi:item.caption.vi,aspectRatio:item.aspectRatio,theme:item.theme,allowedPermissions:item.allowedPermissions});setPreview(item);window.scrollTo({top:0,behavior:"smooth"})}
 async function remove(id:string){const result=await fetch(`/api/studio/embeds?id=${encodeURIComponent(id)}`,{method:"DELETE"}).then(r=>r.json());onStatus(result.ok?"Embed deleted.":result.error);if(result.ok)await refresh()}
 async function assign(slot:EmbedSlotKey,embedId:string){const result=await fetch("/api/studio/embed-assignments",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(embedId?{action:"assign",slot,embedId}:{action:"remove",slot})}).then(r=>r.json());onStatus(result.ok?"Embed assignment updated.":result.error);if(result.ok)await refresh()}
 function permission(name:EmbedBlock["allowedPermissions"][number],checked:boolean){setDraft(value=>({...value,allowedPermissions:checked?[...new Set([...value.allowedPermissions,name])]:value.allowedPermissions.filter(item=>item!==name)}))}
 return <section className="studio-embeds"><header className="embed-studio-intro"><div><p className="eyebrow">URL-first / no raw HTML</p><h1>Embed Library</h1></div><p>Paste an official media URL. Studio detects the provider, normalizes it, and creates a restricted player representation.</p></header><div className="embed-composer"><form onSubmit={inspect}><label>Media or iframe URL<input type="url" required value={draft.url} onChange={e=>{setDraft({...draft,url:e.target.value});setPreview(null)}} placeholder="https://www.youtube.com/watch?v=…"/></label><div className="embed-fields"><label>Title / English<input value={draft.titleEn} onChange={e=>setDraft({...draft,titleEn:e.target.value})}/></label><label>Tiếng Việt<input value={draft.titleVi} onChange={e=>setDraft({...draft,titleVi:e.target.value})}/></label><label>Caption / English<input value={draft.captionEn} onChange={e=>setDraft({...draft,captionEn:e.target.value})}/></label><label>Tiếng Việt<input value={draft.captionVi} onChange={e=>setDraft({...draft,captionVi:e.target.value})}/></label><label>Aspect ratio<select value={draft.aspectRatio} onChange={e=>setDraft({...draft,aspectRatio:e.target.value as Draft["aspectRatio"]})}><option>16:9</option><option>4:3</option><option>1:1</option><option>compact</option></select></label><label>Theme<select value={draft.theme} onChange={e=>setDraft({...draft,theme:e.target.value as Draft["theme"]})}><option>auto</option><option>light</option><option>dark</option></select></label></div><fieldset><legend>Custom iframe permissions — allowlisted hosts only</legend>{(["fullscreen","autoplay","encrypted-media","picture-in-picture"] as const).map(item=><label key={item}><input type="checkbox" checked={draft.allowedPermissions.includes(item)} onChange={e=>permission(item,e.target.checked)}/>{item}</label>)}</fieldset><div className="embed-actions"><button>Detect & preview</button><button type="button" className="studio-secondary" onClick={()=>{setDraft(empty);setPreview(null);setEditing(null)}}>Cancel</button></div></form><aside>{preview?<><div className="embed-detection"><span>{preview.provider}</span><span>{preview.contentType}</span><span>{preview.renderMode}</span></div><EmbedRenderer embed={preview} preview/><p className="embed-privacy">Loading this preview may connect to {preview.provider}. Autoplay is disabled.</p><button onClick={()=>void save()}>{editing?"Update embed":"Save embed"}</button></>:<div className="embed-preview-empty"><Link2/><strong>Preview appears here</strong><span>Nothing is saved until you confirm.</span></div>}</aside></div>
 <div className="embed-library"><h2>Saved embeds</h2>{embeds.length===0?<p className="studio-empty-line">No embed blocks saved.</p>:embeds.map(item=>{const used=assignments.filter(a=>a.embedId===item.id).map(a=>embedSlots[a.slot].label);return <article key={item.id}><div><small>{item.provider} · {item.contentType}</small><h3>{item.title.en||item.title.vi||item.sourceUrl}</h3><a href={item.sourceUrl} target="_blank" rel="noopener noreferrer">Source ↗</a></div><div className="embed-library-preview"><EmbedRenderer embed={item}/></div><div className="embed-library-meta"><code>{item.id}</code><span>{used.length?`Used in: ${used.join(", ")}`:"Not assigned"}</span><div><button onClick={()=>void navigator.clipboard.writeText(item.id)}><Clipboard/>Copy ID</button><button onClick={()=>edit(item)}>Edit</button><button className="studio-danger" onClick={()=>void remove(item.id)}><Trash2/>Delete</button></div></div></article>})}</div>
 <div className="embed-slots"><h2>Content slots</h2>{Object.entries(embedSlots).map(([slot,definition])=><label key={slot}><span><small>{slot}</small><strong>{definition.label}</strong></span><select value={assignments.find(a=>a.slot===slot)?.embedId||""} onChange={e=>void assign(slot as EmbedSlotKey,e.target.value)}><option value="">No embed assigned</option>{embeds.map(item=><option key={item.id} value={item.id}>{item.title.en||item.title.vi||`${item.provider} · ${item.id.slice(0,8)}`}</option>)}</select></label>)}</div></section>
}
