"use client";
import Link from "next/link";
import { Check } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import type { Locale } from "@/data/site.config";
import { trackEvent } from "@/lib/analytics";
import { leadSchema, leadTypeFromService, type LeadType } from "@/lib/lead";
import { parseLeadAttribution, type LeadAttribution } from "@/lib/lead-tracking";

type Field={name:string;en:string;vi:string;type?:"text"|"tel"|"date"|"number"|"select"|"textarea";required?:boolean;options?:string[]};
const commonOptions={yesNo:["Yes","No"],property:["Single-family","Townhome","Condo","Multi-family","Land","Commercial","Other"],format:["Phone","Video call","In person","Not sure yet"]};
const fields:Record<LeadType,Field[]>={
  buyer:[{name:"targetArea",en:"Target area",vi:"Khu vực dự kiến",required:true},{name:"budgetRange",en:"Approximate budget range",vi:"Khoảng ngân sách dự kiến",required:true},{name:"timeline",en:"Purchase timeline",vi:"Thời gian dự kiến mua nhà",required:true},{name:"firstTimeBuyer",en:"First-time buyer",vi:"Mua nhà lần đầu",type:"select",options:commonOptions.yesNo,required:true},{name:"financingStatus",en:"Financing status",vi:"Tình trạng chuẩn bị tài chính",type:"select",options:["Exploring options","Pre-approved","Cash","Need lender guidance","Prefer not to say"],required:true}],
  seller:[{name:"propertyAddress",en:"Property address",vi:"Địa chỉ bất động sản",required:true},{name:"propertyType",en:"Property type",vi:"Loại bất động sản",type:"select",options:commonOptions.property,required:true},{name:"timeline",en:"Expected selling timeline",vi:"Thời gian dự kiến bán",required:true},{name:"mainGoal",en:"Main goal",vi:"Mục tiêu chính",required:true}],
  investor:[{name:"targetArea",en:"Target area",vi:"Khu vực mục tiêu",required:true},{name:"propertyType",en:"Property type",vi:"Loại bất động sản",type:"select",options:commonOptions.property,required:true},{name:"investmentStrategy",en:"Investment strategy",vi:"Chiến lược đầu tư",required:true},{name:"budgetRange",en:"Approximate budget range",vi:"Khoảng ngân sách dự kiến",required:true},{name:"timeline",en:"Timeline",vi:"Thời gian dự kiến",required:true}],
  inspection:[{name:"propertyAddress",en:"Property address",vi:"Địa chỉ bất động sản",required:true},{name:"propertyType",en:"Property type",vi:"Loại bất động sản",type:"select",options:commonOptions.property,required:true},{name:"squareFootage",en:"Approximate square footage (optional)",vi:"Diện tích ước tính (không bắt buộc)",type:"number"},{name:"yearBuilt",en:"Year built (optional)",vi:"Năm xây dựng (không bắt buộc)",type:"number"},{name:"preferredDate",en:"Preferred inspection date",vi:"Ngày kiểm tra mong muốn",type:"date",required:true},{name:"clientRole",en:"Your role",vi:"Vai trò của Anh/Chị",type:"select",options:["Buyer","Seller","Agent","Other"],required:true}],
  "inspection-report-review":[{name:"propertyAddress",en:"Property address (optional)",vi:"Địa chỉ bất động sản (không bắt buộc)"},{name:"reportAvailable",en:"Existing report available",vi:"Đã có báo cáo kiểm tra",type:"select",options:commonOptions.yesNo,required:true},{name:"mainQuestions",en:"Main questions",vi:"Câu hỏi chính",type:"textarea",required:true},{name:"consultationFormat",en:"Preferred consultation format",vi:"Hình thức tư vấn mong muốn",type:"select",options:commonOptions.format,required:true}],
  "spatial-residential":spatialFields(),"spatial-property-selection":spatialFields(),"spatial-business":spatialFields(),"spatial-audit":spatialFields(),
  general:[{name:"topic",en:"Topic",vi:"Chủ đề",type:"select",options:["Real Estate","Home Inspection","Spatial Consultation","Media / Collaboration","General"],required:true}],
};
function spatialFields():Field[]{return [{name:"propertyLocation",en:"Property location",vi:"Vị trí bất động sản",required:true},{name:"propertyType",en:"Property type",vi:"Loại bất động sản",type:"select",options:commonOptions.property,required:true},{name:"primaryObjective",en:"Primary objective",vi:"Mục tiêu chính",required:true},{name:"propertyStatus",en:"Property status",vi:"Tình trạng bất động sản",type:"select",options:["Existing property","Considering purchase","Considering lease","Not sure yet"],required:true},{name:"consultationFormat",en:"Preferred consultation format",vi:"Hình thức tư vấn mong muốn",type:"select",options:commonOptions.format,required:true}]}

const labels:Record<LeadType,[string,string]>={buyer:["Buyer consultation","Tư vấn người mua"],seller:["Seller consultation","Tư vấn người bán"],investor:["Investor consultation","Tư vấn nhà đầu tư"],inspection:["Request an inspection","Yêu cầu kiểm tra nhà"],"inspection-report-review":["Report review","Rà soát báo cáo"],"spatial-residential":["Residential consultation","Tư vấn nhà ở"],"spatial-property-selection":["Property selection","Lựa chọn bất động sản"],"spatial-business":["Business / commercial space","Không gian kinh doanh"],"spatial-audit":["General space audit","Đánh giá không gian tổng quát"],general:["General inquiry","Liên hệ chung"]};
const groups=[{id:"deal",number:"01",types:["buyer","seller","investor"] as LeadType[],en:"DEAL · Real Estate",vi:"DEAL · Bất động sản"},{id:"condition",number:"02",types:["inspection","inspection-report-review"] as LeadType[],en:"CONDITION · Home Inspection",vi:"CONDITION · Kiểm tra nhà"},{id:"space",number:"03",types:["spatial-residential","spatial-property-selection","spatial-business","spatial-audit"] as LeadType[],en:"SPACE · Spatial Consultation",vi:"SPACE · Tư vấn không gian"},{id:"general",number:"04",types:["general"] as LeadType[],en:"GENERAL · Not sure yet",vi:"GENERAL · Chưa chắc dịch vụ phù hợp"}];

export function LeadCapture({locale,initialService,contact=false}:{locale:Locale;initialService?:string|null;contact?:boolean}){
  const vi=locale==="vi";const initial=contact?"general":leadTypeFromService(initialService);const [type,setType]=useState<LeadType|null>(initial);const [status,setStatus]=useState<"idle"|"loading"|"success"|"error">("idle");const [errors,setErrors]=useState<Record<string,string>>({});const startedAt=useRef(0);const attribution=useRef<LeadAttribution>({source:"direct",landingPage:"",currentPage:"",referrer:"",utmSource:"",utmMedium:"",utmCampaign:"",utmContent:"",utmTerm:""});
  useEffect(()=>{const current=parseLeadAttribution(new URLSearchParams(location.search),location.pathname,document.referrer);const saved=sessionStorage.getItem("lead-attribution");const merged=saved?{...JSON.parse(saved),currentPage:location.pathname}:{...current,landingPage:location.pathname};sessionStorage.setItem("lead-attribution",JSON.stringify(merged));attribution.current=merged;trackEvent(contact?"contact_click":"book_page_view")},[contact]);
  const activeGroup=useMemo(()=>groups.find(group=>type&&group.types.includes(type)),[type]);
  function choose(next:LeadType,eventTime:number){setType(next);setStatus("idle");setErrors({});startedAt.current=eventTime;trackEvent("service_selected",{service:next})}
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!type)return;setStatus("loading");setErrors({});const form=new FormData(event.currentTarget);const serviceData=Object.fromEntries(fields[type].map(field=>[field.name,String(form.get(field.name)||"")]));const raw={type,locale,contact:{fullName:form.get("fullName"),email:form.get("email"),phone:String(form.get("phone")||""),preferredLanguage:form.get("preferredLanguage")||locale},serviceData,message:String(form.get("message")||""),attribution:attribution.current,pagePath:location.pathname,consent:form.get("consent")==="on",website:String(form.get("website")||""),completionTimeMs:Math.max(0,Math.round(event.timeStamp-startedAt.current)),reportUploadPlanned:false};const parsed=leadSchema.safeParse(raw);if(!parsed.success){const next:Record<string,string>={};for(const issue of parsed.error.issues)next[String(issue.path.at(-1))]=vi?"Vui lòng hoàn tất trường này.":"Please complete this field.";setErrors(next);setStatus("error");trackEvent("lead_form_error",{service:type});return}try{const response=await fetch("/api/leads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(parsed.data)});const result=await response.json();if(!response.ok)throw new Error(result.error);setStatus("success");trackEvent("lead_form_submitted",{service:type})}catch(error){setErrors({form:error instanceof Error?error.message:"Submission failed"});setStatus("error");trackEvent("lead_form_error",{service:type})}}
  if(status==="success"&&type)return <section className={`lead-success lead-${activeGroup?.id}`} aria-live="polite"><span><Check aria-hidden="true"/></span><p className="eyebrow">{vi?"Đã tiếp nhận":"Request received"}</p><h2>{vi?"Thông tin đã được gửi thành công.":"Your request has been received."}</h2><p>{vi?"Anh Cao sẽ xem xét nội dung và liên hệ bằng thông tin Anh/Chị đã cung cấp.":"Anh Cao will review the details and follow up using the contact information provided."}</p><strong>{labels[type][vi?1:0]}</strong><Link href={`/${locale}/${activeGroup?.id==="deal"?"real-estate":activeGroup?.id==="condition"?"home-inspection":activeGroup?.id==="space"?"spatial-consultation":""}`}>{vi?"Quay lại trang dịch vụ":"Return to service"}</Link></section>;
  return <div className={`lead-capture lead-${activeGroup?.id||"general"}`}>
    {!contact&&<fieldset className="service-selector"><legend>{vi?"01 · Anh/Chị cần hỗ trợ gì?":"01 · What do you need?"}</legend><div>{groups.map(group=><button type="button" aria-pressed={activeGroup?.id===group.id} onClick={event=>choose(group.types[0],event.timeStamp)} key={group.id}><span>{group.number}</span><strong>{vi?group.vi:group.en}</strong></button>)}</div></fieldset>}
    {type&&activeGroup&&<><nav className="lead-pathway-selector" aria-label={vi?"Chọn lộ trình":"Choose pathway"}>{activeGroup.types.map(item=><button type="button" aria-pressed={type===item} onClick={event=>choose(item,event.timeStamp)} key={item}>{labels[item][vi?1:0]}</button>)}</nav><form className="lead-form" onSubmit={submit} noValidate onFocus={event=>{if(startedAt.current===0)startedAt.current=event.timeStamp;trackEvent("lead_form_started",{service:type})}}>
      <div className="lead-form-heading"><span>02</span><div><p className="eyebrow">{vi?"Chi tiết yêu cầu":"Request details"}</p><h2>{labels[type][vi?1:0]}</h2></div></div>
      <div className="lead-field-grid">{fields[type].map(field=><FormField key={field.name} field={field} vi={vi} error={errors[field.name]}/>)}</div>
      <label className="lead-message">{vi?"Thông tin bổ sung":"Additional notes"}<textarea name="message" maxLength={2000} rows={4}/></label>
      <fieldset className="lead-contact"><legend><span>03</span>{vi?"Thông tin liên hệ":"Contact details"}</legend><div className="lead-field-grid"><FormField field={{name:"fullName",en:"Full name",vi:"Họ và tên",required:true}} vi={vi} error={errors.fullName}/><FormField field={{name:"email",en:"Email",vi:"Email",type:"text",required:true}} vi={vi} error={errors.email}/><FormField field={{name:"phone",en:type==="inspection"?"Phone":"Phone (optional)",vi:type==="inspection"?"Số điện thoại":"Số điện thoại (không bắt buộc)",type:"tel",required:type==="inspection"}} vi={vi} error={errors.phone}/><label>{vi?"Ngôn ngữ liên hệ ưu tiên":"Preferred language"}<select name="preferredLanguage" defaultValue={locale}><option value="en">English</option><option value="vi">Tiếng Việt</option></select></label></div></fieldset>
      <label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><label className="checkbox"><input type="checkbox" name="consent" required/><span>{vi?<>Tôi đồng ý để Anh Cao / Spatial Specialist LLC liên hệ về yêu cầu này. Xem <Link href={`/${locale}/privacy`}>Chính sách bảo mật</Link>.</>:<>I agree that Anh Cao / Spatial Specialist LLC may contact me regarding this inquiry. See the <Link href={`/${locale}/privacy`}>Privacy Policy</Link>.</>}</span></label>
      <div aria-live="assertive">{status==="error"&&<p className="form-error" role="alert">{errors.form||(vi?"Vui lòng kiểm tra các trường được đánh dấu.":"Please review the highlighted fields.")}</p>}</div><button className="button button-dark" disabled={status==="loading"}>{status==="loading"?(vi?"Đang gửi…":"Sending…"):(vi?"Gửi yêu cầu":"Send request")}</button><small>{vi?"Không gửi SSN, thông tin tài khoản ngân hàng hoặc tài liệu tài chính nhạy cảm.":"Do not submit SSNs, bank information, or sensitive financial documents."}</small>
    </form></>}
  </div>}

function FormField({field,vi,error}:{field:Field;vi:boolean;error?:string}){const id=`lead-${field.name}`;const label=vi?field.vi:field.en;return <label htmlFor={id}>{label}{field.required&&<span aria-hidden="true"> *</span>}{field.type==="select"?<select id={id} name={field.name} required={field.required} aria-invalid={!!error} defaultValue=""><option value="">{vi?"Chọn một lựa chọn":"Select an option"}</option>{field.options?.map(option=><option key={option}>{option}</option>)}</select>:field.type==="textarea"?<textarea id={id} name={field.name} required={field.required} maxLength={500} rows={3} aria-invalid={!!error}/>:<input id={id} name={field.name} type={field.type||(/^email$/.test(field.name)?"email":"text")} required={field.required} maxLength={field.type==="tel"?40:field.type==="number"?undefined:500} aria-invalid={!!error}/>} {error&&<small className="field-error">{error}</small>}</label>}

export function LeadForm({locale,type="general"}:{locale:Locale;type?:LeadType}){return <LeadCapture locale={locale} initialService={type}/>}

export function ExternalBookingLink({url,locale}:{url:string;locale:Locale}){return <a className="external-booking-link" href={url} target="_blank" rel="noreferrer" onClick={()=>trackEvent("booking_external_click")}>{locale==="vi"?"Chọn thời gian trên lịch":"Schedule a time"}</a>}
