"use client";
import Link from "next/link";
import { ArrowDown, ArrowUp, Copy } from "lucide-react";
import { useState } from "react";
import type { ManagedPage, ManagedSection } from "@/lib/page-manager/types";

export function PageManagerClient({ initialPages }: { initialPages: ManagedPage[] }) {
  const [pages, setPages] = useState(initialPages);
  const [activeId, setActiveId] = useState(initialPages[0]?.id ?? "");
  const [status, setStatus] = useState("");
  const page = pages.find((item) => item.id === activeId);
  function update(patch: Partial<ManagedPage>) { setPages((items) => items.map((item) => item.id === activeId ? { ...item, ...patch } : item)); }
  function updateSections(sections: ManagedSection[]) { update({ sections }); }
  function move(index: number, delta: number) { if (!page) return; const target = index + delta; if (target < 0 || target >= page.sections.length) return; const sections = [...page.sections]; [sections[index], sections[target]] = [sections[target], sections[index]]; updateSections(sections); }
  function duplicate(index: number) { if (!page) return; const clone = { ...structuredClone(page.sections[index]), id: crypto.randomUUID() }; updateSections([...page.sections.slice(0, index + 1), clone, ...page.sections.slice(index + 1)]); }
  async function save(nextStatus: ManagedPage["status"]) { if (!page) return; setStatus("Saving…"); const response = await fetch("/api/studio/pages", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ page: { ...page, status: nextStatus, publishedLocales: nextStatus === "published" ? Object.keys(page.localeContent) : [] } }) }); const result = await response.json(); setStatus(result.ok ? nextStatus === "published" ? "Published" : "Draft saved" : result.error); if (result.ok) setPages((items) => items.map((item) => item.id === result.page.id ? result.page : item)); }
  return <section className="platform-manager"><aside className="platform-manager-list"><p className="eyebrow">Managed pages</p>{pages.map((item) => <button key={item.id} aria-pressed={item.id === activeId} onClick={() => setActiveId(item.id)}><strong>{item.localeContent.en?.title ?? item.slug}</strong><span>{item.visibility} · {item.status}</span></button>)}</aside>{page && <div className="platform-manager-editor"><header><div><p className="eyebrow">Page Manager</p><h1>{page.localeContent.en?.title ?? page.slug}</h1><p>{page.route} · {page.system ? "System page" : "Managed page"}</p></div><div><button onClick={() => void save("draft")}>Save Draft</button><button onClick={() => void save("published")}>Publish</button><Link href={`/en${page.route === "/" ? "" : page.route}?visualPreview=1`} target="_blank">Preview</Link></div></header><div className="platform-manager-meta"><label>English title<input value={page.localeContent.en?.title ?? ""} onChange={(event) => update({ localeContent: { ...page.localeContent, en: { title: event.target.value, description: page.localeContent.en?.description ?? "", seoTitle: page.localeContent.en?.seoTitle ?? "", seoDescription: page.localeContent.en?.seoDescription ?? "" } } })}/></label><label>Visibility<select value={page.visibility} onChange={(event) => update({ visibility: event.target.value as ManagedPage["visibility"] })}><option>public</option><option>hidden</option><option>internal</option></select></label></div><div className="managed-section-list">{page.sections.map((section, index) => <article key={section.id}><div><small>{section.type}</small><strong>{section.id}</strong><span>{section.visible ? "Visible" : "Hidden"}</span></div><div><button aria-label="Move section up" onClick={() => move(index, -1)}><ArrowUp/></button><button aria-label="Move section down" onClick={() => move(index, 1)}><ArrowDown/></button><button aria-label="Duplicate section" onClick={() => duplicate(index)}><Copy/></button><button onClick={() => updateSections(page.sections.map((item) => item.id === section.id ? { ...item, visible: !item.visible } : item))}>{section.visible ? "Hide" : "Show"}</button><Link href={`/studio/page-assets?page=${page.id}`}>Media</Link><Link href={`/studio/visuals?page=${page.id}&section=${section.visualSectionId ?? section.id}`}>Visual</Link></div></article>)}</div><output className="studio-status" aria-live="polite">{status}</output></div>}</section>;
}

