"use client";

import {useEffect,useRef,type CSSProperties} from "react";
import {deterministicScenePoints,getProceduralScene,type ProceduralSceneId} from "@/lib/media/procedural-scenes";

export function ProceduralScene({sceneId,intensity,motionSpeed,className,decorative=true,label}:{sceneId:ProceduralSceneId;intensity?:number;motionSpeed?:number;className?:string;decorative?:boolean;label?:string}){
 const scene=getProceduralScene(sceneId),ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const element=ref.current;if(!element)return;const setState=()=>{element.dataset.documentVisible=String(!document.hidden)};const observer=new IntersectionObserver(entries=>{element.dataset.inView=String(entries[0]?.isIntersecting??false)},{rootMargin:"120px"});observer.observe(element);document.addEventListener("visibilitychange",setState);setState();return()=>{observer.disconnect();document.removeEventListener("visibilitychange",setState)}},[]);
 if(!scene)return null;
 const points=deterministicScenePoints(scene.seed,scene.nodeDensity),style={"--scene-grid":`${scene.gridDensity}px`,"--scene-intensity":String((intensity??scene.intensity)/100),"--scene-speed":String(motionSpeed??scene.motionSpeed),"--scene-glow":`${scene.glow}px`,"--scene-depth":`${scene.depth}px`,"--scene-noise":String(scene.noise/100)} as CSSProperties;
 return <div ref={ref} className={`procedural-scene scene-${scene.palette} composition-${scene.composition} scan-${scene.scan}${className?` ${className}`:""}`} style={style} aria-hidden={decorative||undefined} role={decorative?undefined:"img"} aria-label={decorative?undefined:(label||scene.label)} data-scene-id={scene.id} data-reduced-motion={scene.reducedMotionMode} data-in-view="true" data-document-visible="true"><div className="procedural-scene-field"/><svg className="procedural-scene-network" viewBox="0 0 100 100" preserveAspectRatio="none" focusable="false" aria-hidden="true"><defs><linearGradient id={`signal-${scene.id}`} x1="0" y1="0" x2="1" y2="1"><stop offset="0" stopColor="currentColor" stopOpacity="0"/><stop offset=".5" stopColor="currentColor" stopOpacity=".72"/><stop offset="1" stopColor="currentColor" stopOpacity=".08"/></linearGradient></defs>{points.slice(1).map((point,index)=>{const previous=points[index];return <line key={`l-${point.id}`} x1={previous.x} y1={previous.y} x2={point.x} y2={point.y} pathLength="1" style={{animationDelay:`${point.phase}s`}}/>})}{points.map(point=><circle key={point.id} cx={point.x} cy={point.y} r={point.r} style={{animationDelay:`${point.phase}s`}}/>)}</svg><span className="procedural-scene-scan"/><span className="procedural-scene-frame"/><span className="procedural-scene-radar"/></div>
}
