"use client";

import Image from "next/image";
import {usePathname,useSearchParams} from "next/navigation";
import {useEffect,useMemo,useRef,useState,type CSSProperties} from "react";
import type {MediaPresentation,MediaSlotKey} from "@/lib/media/types";
import {baselineVisualSettings,resolveVisualSettings,visualCssVariables,type VisualConfig,type VisualPageKey} from "@/lib/visuals/config";
import {visualPreviewMessageSchema} from "@/lib/visuals/preview";

export type StoryBackdropItem={slot:MediaSlotKey;url:string;provider:string;mimeType:string;width:number;height:number;presentation:MediaPresentation;draft?:boolean};

export function StoryBackdropShell({children,backdrops,visuals}:{children:React.ReactNode;backdrops:StoryBackdropItem[];visuals:{draft:VisualConfig;published:VisualConfig}}){
  const pathname=usePathname(),searchParams=useSearchParams(),shellRef=useRef<HTMLDivElement>(null),preview=searchParams.get("mediaPreview")==="1",visualPreview=searchParams.get("visualPreview")==="1";
  const page=pathname.match(/^\/(?:en|vi)\/real-estate(?:\/|$)/)?"realEstate":pathname.match(/^\/(?:en|vi)\/home-inspection(?:\/|$)/)?"homeInspection":pathname.match(/^\/(?:en|vi)\/spatial-consultation(?:\/|$)/)?"spatial":pathname.match(/^\/(?:en|vi)\/?$/)?"homepage":null;
  const visualPage:VisualPageKey|null=page==="realEstate"?"deal":page==="homeInspection"?"condition":page==="spatial"?"space":page;
  const locale=pathname.startsWith("/vi")?"vi":"en",persistedVisualConfig=visualPreview?visuals.draft:visuals.published,[liveVisualConfig,setLiveVisualConfig]=useState(persistedVisualConfig),visualConfig=visualPreview?liveVisualConfig:persistedVisualConfig,visualSettings=visualPage?resolveVisualSettings(visualConfig,visualPage,locale):null,customBackdrop=Boolean(visualPage&&(visualConfig.pages[visualPage]?.settings.backdrop||visualConfig.locales[locale]?.[visualPage]?.settings.backdrop||JSON.stringify(visualConfig.global.backdrop)!==JSON.stringify(baselineVisualSettings.backdrop)));
  const selected=useMemo(()=>{if(!page)return null;const candidates=backdrops.filter(item=>preview?item.draft:!item.draft),find=(suffix:string)=>candidates.find(item=>item.slot===`${page}.${suffix}`);return {mobile:find("storyBackdropMobile"),desktop:find("storyBackdropDesktop")}},[backdrops,page,preview]);
  const active=selected?.mobile||selected?.desktop;
  useEffect(()=>{if(!visualPreview||process.env.NODE_ENV==="production"||!visualPage)return;const receive=(event:MessageEvent<unknown>)=>{if(event.origin!==window.location.origin)return;const parsed=visualPreviewMessageSchema.safeParse(event.data);if(parsed.success&&parsed.data.page===visualPage&&parsed.data.locale===locale)setLiveVisualConfig(parsed.data.config)};window.addEventListener("message",receive);return()=>window.removeEventListener("message",receive)},[locale,visualPage,visualPreview]);
  useEffect(()=>{const shell=shellRef.current;if(!shell||!active||!active.presentation.enabled||active.presentation.mode==="none")return;let frame=0;const reducedMotion=window.matchMedia("(prefers-reduced-motion: reduce)"),mobileViewport=window.matchMedia("(max-width: 768px)"),layer=shell.querySelector<HTMLElement>(".story-backdrop-layer");const visiblePrimary=()=>[...shell.querySelectorAll<HTMLElement>(".story-backdrop-primary img,.story-backdrop-primary video")].find(item=>item.getClientRects().length>0);const update=()=>{frame=0;const primary=visiblePrimary(),sourceWidth=Number(primary?.getAttribute("width"))||active.width,sourceHeight=Number(primary?.getAttribute("height"))||active.height,mobileHeight=mobileViewport.matches&&sourceWidth>0?`${window.innerWidth*sourceHeight/sourceWidth}px`:"auto";if(shell.style.getPropertyValue("--story-primary-mobile-height")!==mobileHeight)shell.style.setProperty("--story-primary-mobile-height",mobileHeight);const rect=shell.getBoundingClientRect(),distance=Math.max(1,rect.height-window.innerHeight),progress=Math.min(1,Math.max(0,-rect.top/distance)),travel=Math.max(0,(primary?.getBoundingClientRect().height||0)-(layer?.clientHeight||window.innerHeight)),start=Math.min(1,Math.max(0,active.presentation.startPosition)),end=Math.min(1,Math.max(start,active.presentation.endPosition)),position=reducedMotion.matches?(start+end)/2:start+progress*(end-start);shell.style.setProperty("--story-progress",String(progress));shell.style.setProperty("--story-travel",`${travel}px`);shell.style.setProperty("--story-primary-y",`${-travel*position}px`);shell.dataset.reducedMotion=String(reducedMotion.matches)};const schedule=()=>{if(!frame)frame=requestAnimationFrame(update)},observer=new ResizeObserver(schedule);observer.observe(shell);if(layer)observer.observe(layer);shell.querySelectorAll<HTMLElement>(".story-backdrop-primary img,.story-backdrop-primary video").forEach(item=>observer.observe(item));update();window.addEventListener("scroll",schedule,{passive:true});window.addEventListener("resize",schedule,{passive:true});reducedMotion.addEventListener("change",update);mobileViewport.addEventListener("change",update);return()=>{observer.disconnect();cancelAnimationFrame(frame);window.removeEventListener("scroll",schedule);window.removeEventListener("resize",schedule);reducedMotion.removeEventListener("change",update);mobileViewport.removeEventListener("change",update)}},[active]);
  if(!active||!active.presentation.enabled||active.presentation.mode==="none"||visualSettings?.backdrop.enabled===false)return <>{children}</>;
  const overlay=active.presentation;
  const shellStyle={"--story-focal-x":`${overlay.focalX*100}%`,"--story-focal-y":`${overlay.focalY*100}%`,"--story-primary-y":"0px","--story-primary-mobile-height":"auto","--story-travel":"0px",...(visualSettings?visualCssVariables(visualSettings):{})} as CSSProperties;
  const overlayOpacity=visualSettings&&visualSettings.backdrop.overlayStrength>0?visualSettings.backdrop.overlayStrength/100:overlay.overlayStrength;
  return <div ref={shellRef} style={shellStyle} className={`story-backdrop-shell contrast-${overlay.textContrastMode}`} data-mode={overlay.mode} data-visual-backdrop-custom={customBackdrop} data-reduced-fallback={overlay.reducedMotionFallback} data-testid="story-backdrop-shell"><div className="story-backdrop-layer" aria-hidden="true">{selected?.mobile&&<BackdropMedia item={selected.mobile} className="story-backdrop-mobile"/>}{selected?.desktop&&<BackdropMedia item={selected.desktop} className="story-backdrop-desktop"/>}<span style={{backgroundColor:overlay.overlayColor,opacity:overlayOpacity}}/></div><div className="story-backdrop-content">{preview&&active.draft&&<div className="development-preview-label">Development Preview</div>}{children}</div></div>
}
function BackdropMedia({item,className}:{item:StoryBackdropItem;className:string}){const ambientStyle={backgroundImage:`url(${JSON.stringify(item.url)})`} as CSSProperties,mediaStyle={"--story-aspect":`${item.width||1} / ${item.height||1}`} as CSSProperties;return <div className={`${className} story-backdrop-media`} style={mediaStyle}>{!item.mimeType.startsWith("video/")&&<div className="story-backdrop-ambient" style={ambientStyle}/>}<div className="story-backdrop-primary">{item.mimeType.startsWith("video/")?<video src={item.url} muted playsInline loop autoPlay={false}/>:<Image src={item.url} alt="" width={item.width||1} height={item.height||1} loading="eager" fetchPriority="high" sizes="(max-width: 768px) 100vw, 80vw" unoptimized={item.provider==="local"}/>}</div></div>}
