import Link from "next/link";
import {brandPromises,brandThesis,buyerProcess,sellerProcess,strategicLenses} from "@/data/strategy";
import type {Locale} from "@/data/site.config";

const viPromiseTitles=["Nhìn vấn đề sớm hơn","Chi tiêu chuẩn bị có chọn lọc","Tạo trải nghiệm tài sản rõ ràng hơn","Trình bày tài sản phức tạp mạch lạc hơn"];
const viSellerSteps=["Chẩn đoán","Ưu tiên","Chuẩn bị","Định vị","Ra mắt","Điều chỉnh"];
const viBuyerSteps=["Bối cảnh","Rủi ro","Phù hợp","Quyết định"];
const conditionSteps={en:["Visible","Accessible","Documented","Prioritized"],vi:["Quan sát được","Tiếp cận được","Được ghi nhận","Được ưu tiên"]};
const spaceSteps={en:["Orientation","Zones","Circulation","Interpretation (optional)"],vi:["Phương hướng","Phân vùng","Lưu thông","Diễn giải (tùy chọn)"]};

export function BrandClaritySection({locale}:{locale:Locale}){const vi=locale==="vi";return <section className="brand-clarity-section"><div><p className="eyebrow">{vi?"Hiểu tài sản rõ hơn":"Property clarity"}</p><h2>{vi?"Rõ hơn trước khi cam kết.":brandThesis.public}</h2><p>{vi?"Hiểu, chuẩn bị và đánh giá tài sản rõ ràng hơn trước những quyết định quan trọng.":"Understand, prepare, and evaluate property more clearly before important decisions."}</p></div><ol>{brandPromises.map((promise,index)=><li key={promise.key}><span>0{index+1}</span><strong>{vi?viPromiseTitles[index]:promise.title}</strong></li>)}</ol></section>}

export function ServiceClaritySection({locale,service}:{locale:Locale;service:"deal"|"condition"|"space"}){const vi=locale==="vi",lens=strategicLenses[service];if(service==="deal")return <section className="service-clarity-section deal-strategy"><header><p className="eyebrow">{vi?"Khung quyết định":"Decision framework"}</p><h2>{vi?"Bối cảnh trước. Quyết định sau.":lens.question}</h2><p>{vi?"Bối cảnh giao dịch, định vị, người mua, người bán và thị trường.":lens.value}</p></header><div className="strategy-process"><article><span>{vi?"Người bán":"Seller"}</span>{(vi?viSellerSteps:sellerProcess).map((step,index)=><b key={step}>{index+1}. {step}</b>)}</article><article><span>{vi?"Người mua":"Buyer"}</span>{(vi?viBuyerSteps:buyerProcess).map((step,index)=><b key={step}>{index+1}. {step}</b>)}</article></div><Link href={`/${locale}/book?service=real-estate`}>{vi?"Lập kế hoạch bước tiếp theo":"Plan your next move"}</Link></section>;if(service==="condition")return <section className="service-clarity-section condition-strategy"><header><p className="eyebrow">{vi?"Logic quan sát":"Observation logic"}</p><h2>{vi?"Tình trạng tạo ra câu hỏi tốt hơn.":lens.question}</h2><p>{vi?"Quan sát trong phạm vi tiếp cận, ghi nhận giới hạn và sắp xếp câu hỏi cần theo dõi.":lens.value}</p></header><ol>{conditionSteps[locale].map((step,index)=><li key={step}><span>0{index+1}</span><strong>{step}</strong></li>)}</ol></section>;return <section className="service-clarity-section space-strategy"><header><p className="eyebrow">{vi?"Logic không gian":"Spatial logic"}</p><h2>{vi?"Đọc không gian trước khi diễn giải.":lens.question}</h2><p>{vi?"Phương hướng, bố cục, lưu thông, điểm đến, riêng tư, ánh sáng và các vùng chức năng.":lens.value}</p></header><div>{spaceSteps[locale].map((step,index)=><span key={step}><b>{index+1}</b>{step}</span>)}</div></section>}
