"use client";
import Image from "next/image";
import {useMemo,useRef,useState} from "react";
import {ImageIcon,Library,Link2,PanelTop,Search,Upload} from "lucide-react";
import {EmbedStudio} from "@/components/embed-studio";
import type {EmbedAssignment,EmbedBlock} from "@/lib/embeds/types";
import {mediaSlots,type MediaAsset,type MediaAssignment,type MediaPresentation,type MediaSlotKey} from "@/lib/media/types";
import {executeUpload,type UploadGate} from "@/lib/media/upload-flow";

type StudioAsset=MediaAsset&{usedBy:MediaSlotKey[]};type View="library"|"assets"|"embeds";
export function StudioClient({initialAssets,initialAssignments,initialEmbeds,initialEmbedAssignments}:{initialAssets:StudioAsset[];initialAssignments:MediaAssignment[];initialEmbeds:EmbedBlock[];initialEmbedAssignments:EmbedAssignment[]}){const [view,setView]=useState<View>("library");const [assets,setAssets]=useState<StudioAsset[]>(initialAssets);const [assignments,setAssignments]=useState<MediaAssignment[]>(initialAssignments);const [selected,setSelected]=useState<string|null>(null);const [query,setQuery]=useState("");const [status,setStatus]=useState("");const [uploadState,setUploadState]=useState<"idle"|"uploading"|"success"|"error">("idle");const uploadGate=useRef<UploadGate>({active:false});async function load(){const [media,assigned]=await Promise.all([fetch("/api/studio/media").then(r=>r.json()),fetch("/api/studio/assignments").then(r=>r.json())]);if(media.ok)setAssets(media.assets);if(assigned.ok)setAssignments(assigned.assignments)}const active=assets.find(asset=>asset.id===selected)||null;const filtered=useMemo(()=>assets.filter(asset=>`${asset.originalFilename} ${asset.title.en} ${asset.title.vi}`.toLowerCase().includes(query.toLowerCase())),[assets,query]);
  async function upload(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;const formData=new FormData(formElement);if(uploadState==="uploading"||uploadGate.current.active)return;setUploadState("uploading");setStatus("Uploading…");formElement.querySelectorAll("input,button").forEach(control=>{(control as HTMLInputElement|HTMLButtonElement).disabled=true});const outcome=await executeUpload({gate:uploadGate.current,form:formElement,request:async()=>{const response=await fetch("/api/studio/media",{method:"POST",body:formData});return response.json()}});formElement.querySelectorAll("input,button").forEach(control=>{(control as HTMLInputElement|HTMLButtonElement).disabled=false});if(outcome.kind==="duplicate")return;if(outcome.kind==="error"){setUploadState("error");setStatus(outcome.error);return}setUploadState("success");setStatus("Image uploaded.");if(outcome.asset?.id)setSelected(outcome.asset.id);await load()}
  async function update(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!active)return;const form=new FormData(event.currentTarget);const text=(name:string)=>({en:String(form.get(`${name}.en`)||""),vi:String(form.get(`${name}.vi`)||"")});const payload={id:active.id,title:text("title"),alt:text("alt"),caption:text("caption"),focalPoint:{x:Number(form.get("focalX")),y:Number(form.get("focalY"))}};const result=await fetch("/api/studio/media",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}).then(r=>r.json());setStatus(result.ok?"Metadata saved.":result.error);if(result.ok)await load()}
  async function removeAsset(){if(!active||active.provider==="static")return;const result=await fetch(`/api/studio/media?id=${encodeURIComponent(active.id)}`,{method:"DELETE"}).then(r=>r.json());setStatus(result.ok?"Image removed.":result.error);if(result.ok){setSelected(null);await load()}}
  async function assign(slot:MediaSlotKey,assetId:string,presentation:MediaPresentation={mode:"cover",overlayStrength:.35}){const result=await fetch("/api/studio/assignments",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"assign",slot,assetId,presentation})}).then(r=>r.json());setStatus(result.ok?`Assigned to ${mediaSlots[slot].label}.`:result.error);if(result.ok)await load()}
  async function unassign(slot:MediaSlotKey){const result=await fetch("/api/studio/assignments",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"remove",slot})}).then(r=>r.json());setStatus(result.ok?"Assignment removed.":result.error);if(result.ok)await load()}
  return <><nav className="studio-nav" aria-label="Studio sections"><button aria-pressed={view==="library"} onClick={()=>setView("library")}><Library/>Media Library</button><button aria-pressed={view==="assets"} onClick={()=>setView("assets")}><PanelTop/>Page Assets</button><button aria-pressed={view==="embeds"} onClick={()=>setView("embeds")}><Link2/>Embeds</button><span>Content Blocks / Future</span></nav><div className="studio-status" role="status" aria-live="polite">{status}</div>
  {view==="library"&&<section className="studio-library"><div className="studio-tools"><form onSubmit={upload}><label><Upload/><span>Upload image</span><input type="file" name="file" accept="image/jpeg,image/png,image/webp,image/avif" required/></label><button>Upload</button></form><label className="studio-search"><Search/><span className="sr-only">Search media</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search filename or title"/></label><small>JPEG · PNG · WebP · AVIF · 10 MB max</small></div><div className="studio-media-layout"><div className="studio-media-grid">{filtered.map(asset=><button className="studio-media-item" aria-pressed={selected===asset.id} onClick={()=>setSelected(asset.id)} key={asset.id}><span className="studio-thumbnail"><Image src={asset.url} alt="" fill sizes="240px" unoptimized style={{objectPosition:`${asset.focalPoint.x*100}% ${asset.focalPoint.y*100}%`}}/></span><strong>{asset.title.en||asset.title.vi||asset.originalFilename}</strong><small>{asset.provider} · {formatBytes(asset.fileSize)}</small>{asset.usedBy.length>0&&<b>{asset.usedBy.length} use{asset.usedBy.length>1?"s":""}</b>}</button>)}</div>{active&&<aside className="studio-inspector"><div className="studio-preview"><Image src={active.url} alt="" fill sizes="420px" unoptimized style={{objectPosition:`${active.focalPoint.x*100}% ${active.focalPoint.y*100}%`}}/></div><p>{active.originalFilename}</p><small>{active.width||"?"} × {active.height||"?"} · {active.mimeType}</small><form onSubmit={update}><MetadataPair name="title" label="Title" asset={active}/><MetadataPair name="alt" label="Alt text" asset={active}/>{!active.alt.en&&!active.alt.vi&&<p className="studio-warning">Meaningful public images need approved alt text before assignment.</p>}<MetadataPair name="caption" label="Caption" asset={active}/><fieldset><legend>Focal position</legend><label>X<input name="focalX" type="number" min="0" max="1" step="0.05" defaultValue={active.focalPoint.x}/></label><label>Y<input name="focalY" type="number" min="0" max="1" step="0.05" defaultValue={active.focalPoint.y}/></label></fieldset><button>Save metadata</button></form><div className="studio-usage"><strong>Used in</strong>{active.usedBy.length?active.usedBy.map(slot=><span key={slot}>{mediaSlots[slot].label}</span>):<span>Not assigned</span>}</div>{active.provider==="local"&&<button className="studio-danger" onClick={removeAsset}>Delete uploaded image</button>}</aside>}</div></section>}
  {view==="assets"&&<PageAssets assets={assets} assignments={assignments} onAssign={assign} onRemove={unassign}/>} {view==="embeds"&&<EmbedStudio initialEmbeds={initialEmbeds} initialAssignments={initialEmbedAssignments} onStatus={setStatus}/>}</>}

function MetadataPair({name,label,asset}:{name:"title"|"alt"|"caption";label:string;asset:MediaAsset}){return <fieldset><legend>{label}</legend><label>English<input name={`${name}.en`} defaultValue={asset[name].en} maxLength={500}/></label><label>Tiếng Việt<input name={`${name}.vi`} defaultValue={asset[name].vi} maxLength={500}/></label></fieldset>}
function PageAssets({assets,assignments,onAssign,onRemove}:{assets:StudioAsset[];assignments:MediaAssignment[];onAssign:(slot:MediaSlotKey,id:string,presentation?:MediaPresentation)=>Promise<void>;onRemove:(slot:MediaSlotKey)=>Promise<void>}){const categories=[...new Set(Object.values(mediaSlots).map(item=>item.category))];return <section className="studio-page-assets">{categories.map(category=><div key={category}><h2>{category}</h2><div>{(Object.entries(mediaSlots) as Array<[MediaSlotKey,(typeof mediaSlots)[MediaSlotKey]]>).filter(([,item])=>item.category===category).map(([slot,definition])=>{const assignment=assignments.find(item=>item.slot===slot);const asset=assets.find(item=>item.id===assignment?.assetId);return <article key={slot}><div><small>{slot}</small><h3>{definition.label}</h3>{definition.meaningful&&!asset?.alt.en&&!asset?.alt.vi&&asset&&<span>Alt text needed</span>}</div><div className="studio-slot-preview">{asset?<Image src={asset.url} alt="" fill sizes="180px" unoptimized style={{objectPosition:`${asset.focalPoint.x*100}% ${asset.focalPoint.y*100}%`}}/>:<ImageIcon/>}</div><label>Assigned media<select value={assignment?.assetId||""} onChange={event=>event.target.value?void onAssign(slot,event.target.value,assignment?.presentation):void onRemove(slot)}><option value="">No image assigned</option>{assets.map(item=><option key={item.id} value={item.id}>{item.title.en||item.title.vi||item.originalFilename}</option>)}</select></label>{slot==="homepage.heroBackground"&&assignment&&<><label>Presentation<select value={assignment.presentation.mode} onChange={event=>void onAssign(slot,assignment.assetId,{...assignment.presentation,mode:event.target.value as MediaPresentation["mode"]})}><option value="cover">Cover</option><option value="editorial-panel">Contained editorial panel</option><option value="background-overlay">Background with overlay</option><option value="texture">Subtle texture</option></select></label><label>Overlay strength<input type="range" min="0" max="0.9" step="0.05" value={assignment.presentation.overlayStrength} onChange={event=>void onAssign(slot,assignment.assetId,{...assignment.presentation,overlayStrength:Number(event.target.value)})}/></label></>}{assignment&&<button onClick={()=>void onRemove(slot)}>Remove</button>}</article>})}</div></div>)}</section>}
function formatBytes(value:number){return value<1024?`${value} B`:value<1024*1024?`${Math.round(value/1024)} KB`:`${(value/1024/1024).toFixed(1)} MB`}
