"use client";

import Link from "next/link";
import {useEffect,useRef,useState,type CSSProperties} from "react";
import {applyGlobalVisualPreset,applyVisualPreset,baselineVisualConfig,baselineVisualSettings,resolveVisualSettings,visualConfigSchema,visualCssVariables,visualPageKeys,visualPresets,visualSections,type VisualConfig,type VisualPageKey,type VisualPresetKey,type VisualSettings,type VisualSettingsOverride} from "@/lib/visuals/config";
import {acceptPublishedVisuals,acceptSavedDraft,countVisualChanges,createVisualEditorState,isVisualConfigEqual,setVisualOperation,setWorkingVisualConfig,type VisualEditorOperation} from "@/lib/visuals/editor-state";
import {createVisualPreviewMessage,visualPreviewAttributes,visualPreviewReadyMessageSchema} from "@/lib/visuals/preview";

type Scope="shared"|"en"|"vi";
type Group=Exclude<keyof VisualSettings,"accent">;
type VisualTarget="global"|VisualPageKey;
type StoreResponse={ok:boolean;draft:VisualConfig;published:VisualConfig;draftUpdatedAt:string|null;publishedAt:string|null;error?:string};
const pageLabels:Record<VisualTarget,string>={global:"Global system",homepage:"Homepage",deal:"DEAL / Real Estate",condition:"CONDITION / Home Inspection",space:"SPACE / Spatial Consultation",videos:"Videos",guides:"Guides",contact:"Contact",booking:"Booking",footer:"Footer"};
const routes:Record<VisualPageKey,string>={homepage:"",deal:"real-estate",condition:"home-inspection",space:"spatial-consultation",videos:"videos",guides:"guides",contact:"contact",booking:"book",footer:""};
const operationLabels:Record<VisualEditorOperation,string>={idle:"WORKING DRAFT",saving:"SAVING", "draft-saved":"DRAFT SAVED","save-failed":"SAVE FAILED",publishing:"PUBLISHING",published:"PUBLISHED","publish-failed":"PUBLISH FAILED"};

export function VisualDirectorClient({initialDraft,initialPublished,initialPage="homepage",initialScope="shared",draftUpdatedAt,publishedAt}:{initialDraft:VisualConfig;initialPublished:VisualConfig;initialPage?:VisualPageKey;initialScope?:Scope;draftUpdatedAt:string|null;publishedAt:string|null}){
  const [editor,setEditor]=useState(()=>createVisualEditorState(initialDraft,initialPublished,draftUpdatedAt,publishedAt));
  const [page,setPage]=useState<VisualTarget>(initialPage),[scope,setScope]=useState<Scope>(initialScope),[section,setSection]=useState(""),[previewMode,setPreviewMode]=useState<"composition"|"full-page">("composition");
  const iframeRef=useRef<HTMLIFrameElement>(null),busy=editor.operation==="saving"||editor.operation==="publishing",locale=scope==="vi"?"vi":"en",previewPage=page==="global"?"homepage":page;
  const resolved=page==="global"?editor.previewConfig.global:resolveVisualSettings(editor.previewConfig,page,locale,section||undefined),variables=visualCssVariables(resolved) as CSSProperties,attributes=visualPreviewAttributes(resolved);
  const previewHref=`/${locale}/${routes[previewPage]}?visualPreview=1`,unsavedChanges=countVisualChanges(editor.workingVisualConfig,editor.savedDraftConfig),draftDiffersFromPublished=!isVisualConfigEqual(editor.savedDraftConfig,editor.publishedConfig);

  useEffect(()=>{if(previewMode!=="full-page")return;iframeRef.current?.contentWindow?.postMessage(createVisualPreviewMessage(editor.previewConfig,previewPage,locale),window.location.origin)},[editor.previewConfig,locale,previewMode,previewPage]);
  useEffect(()=>{
    if(previewMode!=="full-page")return;
    const receive=(event:MessageEvent<unknown>)=>{
      if(event.origin!==window.location.origin||event.source!==iframeRef.current?.contentWindow)return;
      const parsed=visualPreviewReadyMessageSchema.safeParse(event.data);
      if(!parsed.success||parsed.data.page!==previewPage||parsed.data.locale!==locale)return;
      iframeRef.current?.contentWindow?.postMessage(createVisualPreviewMessage(editor.previewConfig,previewPage,locale),window.location.origin);
    };
    window.addEventListener("message",receive);return()=>window.removeEventListener("message",receive);
  },[editor.previewConfig,locale,previewMode,previewPage]);

  function setWorking(updater:(config:VisualConfig)=>VisualConfig){setEditor(current=>setWorkingVisualConfig(current,visualConfigSchema.parse(updater(current.workingVisualConfig))))}
  function overrideTarget(next:VisualConfig){if(scope==="shared")return next.pages;next.locales[scope]??={};return next.locales[scope]!}
  function updateGroup<K extends Group>(group:K,patch:Partial<VisualSettings[K]>){setWorking(current=>{const next=structuredClone(current);if(page==="global"){next.global={...next.global,[group]:{...next.global[group],...patch}};return next}const target=overrideTarget(next),entry=target[page]??{settings:{},sections:{}};if(section)entry.sections[section]={...entry.sections[section],[group]:{...entry.sections[section]?.[group],...patch}} as VisualSettingsOverride;else entry.settings={...entry.settings,[group]:{...entry.settings[group],...patch}} as VisualSettingsOverride;target[page]=entry;return next})}
  function updateAccent(accent:VisualSettings["accent"]){setWorking(current=>{const next=structuredClone(current);if(page==="global"){next.global.accent=accent;return next}const target=overrideTarget(next),entry=target[page]??{settings:{},sections:{}};if(section)entry.sections[section]={...entry.sections[section],accent};else entry.settings={...entry.settings,accent};target[page]=entry;return next})}
  function resetField(group:Group|"accent",field?:string){setWorking(current=>{const next=structuredClone(current);if(page==="global"){if(group==="accent")next.global.accent=baselineVisualSettings.accent;else{const target=next.global[group] as unknown as Record<string,unknown>,baseline=baselineVisualSettings[group] as unknown as Record<string,unknown>;if(field)target[field]=baseline[field]}return next}const target=overrideTarget(next),entry=target[page];if(!entry)return next;const selected=section?entry.sections[section]:entry.settings;if(!selected)return next;if(group==="accent")delete selected.accent;else{const groupValue=selected[group] as unknown as Record<string,unknown>|undefined;if(groupValue&&field){delete groupValue[field];if(Object.keys(groupValue).length===0)delete (selected as unknown as Record<string,unknown>)[group]}}return next})}
  function applyPreset(preset:VisualPresetKey){setWorking(current=>page==="global"?applyGlobalVisualPreset(current,preset):applyVisualPreset(current,page,preset))}
  function resetSelectedSection(){if(page!=="global"&&section)setWorking(current=>{const next=structuredClone(current),target=overrideTarget(next),entry=target[page];if(entry)delete entry.sections[section];return next})}
  function resetSelectedPage(){setEditor(current=>{const next=structuredClone(current.workingVisualConfig),saved=current.savedDraftConfig;if(page==="global")next.global=structuredClone(saved.global);else{const target=scope==="shared"?next.pages:(next.locales[scope]??={}),source=scope==="shared"?saved.pages:saved.locales[scope];if(source?.[page])target[page]=structuredClone(source[page]);else delete target[page]}return setWorkingVisualConfig(current,visualConfigSchema.parse(next))})}
  function resetToGlobal(){if(page==="global"){setEditor(current=>setWorkingVisualConfig(current,structuredClone(baselineVisualConfig)));return}setWorking(current=>{const next=structuredClone(current),target=overrideTarget(next);delete target[page];return next})}

  async function request(action:"save-draft"|"publish"){
    const submitted=structuredClone(editor.workingVisualConfig);setEditor(current=>setVisualOperation(current,action==="publish"?"publishing":"saving"));
    try{
      const response=await fetch("/api/studio/visuals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,config:submitted})}),data=await response.json() as StoreResponse;if(!response.ok||!data.ok)throw new Error(data.error||"Visual configuration update failed.");
      const parsedDraft=visualConfigSchema.parse(data.draft),parsedPublished=visualConfigSchema.parse(data.published);
      setEditor(current=>{const changedDuringRequest=!isVisualConfigEqual(current.workingVisualConfig,submitted),accepted=action==="publish"?acceptPublishedVisuals(current,parsedPublished,data.draftUpdatedAt??new Date().toISOString(),data.publishedAt??new Date().toISOString()):acceptSavedDraft(current,parsedDraft,data.draftUpdatedAt??new Date().toISOString());return changedDuringRequest?{...accepted,workingVisualConfig:current.workingVisualConfig,previewConfig:current.previewConfig}:accepted});
    }catch(error){setEditor(current=>setVisualOperation(current,action==="publish"?"publish-failed":"save-failed",error instanceof Error?error.message:"Visual configuration update failed."))}
  }
  function sendPreview(){iframeRef.current?.contentWindow?.postMessage(createVisualPreviewMessage(editor.previewConfig,previewPage,locale),window.location.origin)}

  const reset=(group:Group|"accent",field?:string)=>()=>resetField(group,field);
  return <section className="visual-director">
    <header className="visual-director-heading"><div><p className="eyebrow">Studio Visual Director</p><h1>Direct the visual system without editing code.</h1><p>Working changes preview immediately. Save creates a durable draft; Publish updates public pages.</p></div><div className={`visual-status ${editor.error?"is-error":""}`} role="status" aria-live="polite"><span>{operationLabels[editor.operation]}</span><strong>{unsavedChanges?`${unsavedChanges} unsaved changes`:draftDiffersFromPublished?"Draft Saved":"Published"}</strong><small>Draft {editor.draftUpdatedAt?new Date(editor.draftUpdatedAt).toLocaleString():"not saved"}</small><small>Published {editor.publishedAt?new Date(editor.publishedAt).toLocaleString():"Baseline V1"}</small>{editor.error&&<p>{editor.error}</p>}</div></header>
    <div className="visual-director-toolbar">
      <label>Page<select value={page} onChange={event=>{const next=event.target.value as VisualTarget;setPage(next);if(next==="global")setScope("shared");setSection("")}}><option value="global">Global system</option>{visualPageKeys.map(key=><option value={key} key={key}>{pageLabels[key]}</option>)}</select></label>
      <label>Override scope<select value={scope} disabled={page==="global"} onChange={event=>setScope(event.target.value as Scope)}><option value="shared">Shared / inherited</option><option value="en">English override</option><option value="vi">Vietnamese override</option></select></label>
      <label>Section<select value={section} disabled={page==="global"} onChange={event=>setSection(event.target.value)}><option value="">{page==="global"?"All pages":"Whole page"}</option>{page==="global"?null:visualSections[page].map(key=><option key={key} value={key}>{key}</option>)}</select></label>
      <div className="visual-presets" aria-label="Visual presets">{Object.keys(visualPresets).map(key=><button type="button" onClick={()=>applyPreset(key as VisualPresetKey)} key={key}><span className="visual-preset-chip" data-preset={key} aria-hidden="true"/>{key}</button>)}</div>
    </div>
    <div className="visual-director-layout">
      <form className="visual-controls" aria-busy={busy} onSubmit={event=>{event.preventDefault();void request("save-draft")}}>
        <fieldset><legend>Accent + surface</legend><SelectControl label="Accent" value={resolved.accent} options={["service-default","mint","brass","sage","neutral"]} onChange={value=>updateAccent(value as VisualSettings["accent"])} onReset={reset("accent")}/><SelectControl label="Surface" value={resolved.surface.mode} options={["clear","soft","light","dark","glass"]} onChange={value=>updateGroup("surface",{mode:value as VisualSettings["surface"]["mode"]})} onReset={reset("surface","mode")}/><SelectControl label="Tint" value={resolved.surface.tint} options={["neutral","ivory","mint","sage","ink"]} onChange={value=>updateGroup("surface",{tint:value as VisualSettings["surface"]["tint"]})} onReset={reset("surface","tint")}/><RangeControl label="Surface opacity" value={resolved.surface.opacity} min={0} max={100} onChange={value=>updateGroup("surface",{opacity:value})} onReset={reset("surface","opacity")}/><RangeControl label="Glass blur" value={resolved.surface.blur} min={0} max={48} onChange={value=>updateGroup("surface",{blur:value})} onReset={reset("surface","blur")}/><RangeControl label="Border strength" value={resolved.surface.borderStrength} min={0} max={100} onChange={value=>updateGroup("surface",{borderStrength:value})} onReset={reset("surface","borderStrength")}/><RangeControl label="Shadow strength" value={resolved.surface.shadowStrength} min={0} max={100} onChange={value=>updateGroup("surface",{shadowStrength:value})} onReset={reset("surface","shadowStrength")}/></fieldset>
        <fieldset><legend>Backdrop</legend><div className="visual-check-row"><label className="visual-check"><input type="checkbox" checked={resolved.backdrop.enabled} onChange={event=>updateGroup("backdrop",{enabled:event.target.checked})}/>Backdrop enabled</label><ResetButton label="Backdrop enabled" onClick={reset("backdrop","enabled")}/></div><RangeControl label="Primary opacity" value={resolved.backdrop.primaryOpacity} min={0} max={100} onChange={value=>updateGroup("backdrop",{primaryOpacity:value})} onReset={reset("backdrop","primaryOpacity")}/><RangeControl label="Primary brightness" value={resolved.backdrop.primaryBrightness} min={40} max={160} onChange={value=>updateGroup("backdrop",{primaryBrightness:value})} onReset={reset("backdrop","primaryBrightness")}/><RangeControl label="Primary saturation" value={resolved.backdrop.primarySaturation} min={0} max={180} onChange={value=>updateGroup("backdrop",{primarySaturation:value})} onReset={reset("backdrop","primarySaturation")}/><RangeControl label="Primary contrast" value={resolved.backdrop.primaryContrast} min={50} max={160} onChange={value=>updateGroup("backdrop",{primaryContrast:value})} onReset={reset("backdrop","primaryContrast")}/><RangeControl label="Ambient opacity" value={resolved.backdrop.ambientOpacity} min={0} max={100} onChange={value=>updateGroup("backdrop",{ambientOpacity:value})} onReset={reset("backdrop","ambientOpacity")}/><RangeControl label="Ambient blur" value={resolved.backdrop.ambientBlur} min={0} max={48} onChange={value=>updateGroup("backdrop",{ambientBlur:value})} onReset={reset("backdrop","ambientBlur")}/><RangeControl label="Ambient brightness" value={resolved.backdrop.ambientBrightness} min={20} max={120} onChange={value=>updateGroup("backdrop",{ambientBrightness:value})} onReset={reset("backdrop","ambientBrightness")}/><RangeControl label="Ambient saturation" value={resolved.backdrop.ambientSaturation} min={0} max={160} onChange={value=>updateGroup("backdrop",{ambientSaturation:value})} onReset={reset("backdrop","ambientSaturation")}/><RangeControl label="Overlay" value={resolved.backdrop.overlayStrength} min={0} max={100} onChange={value=>updateGroup("backdrop",{overlayStrength:value})} onReset={reset("backdrop","overlayStrength")}/><SelectControl label="Alignment" value={resolved.backdrop.alignment} options={["left","center","right"]} onChange={value=>updateGroup("backdrop",{alignment:value as VisualSettings["backdrop"]["alignment"]})} onReset={reset("backdrop","alignment")}/><RangeControl label="Scroll intensity" value={resolved.backdrop.panIntensity} min={0} max={100} onChange={value=>updateGroup("backdrop",{panIntensity:value})} onReset={reset("backdrop","panIntensity")}/></fieldset>
        <fieldset><legend>Typography</legend><SelectControl label="Display scale" value={resolved.typography.displayScale} options={["compact","standard","expressive"]} onChange={value=>updateGroup("typography",{displayScale:value as VisualSettings["typography"]["displayScale"]})} onReset={reset("typography","displayScale")}/><SelectControl label="Body scale" value={resolved.typography.bodyScale} options={["compact","standard","generous"]} onChange={value=>updateGroup("typography",{bodyScale:value as VisualSettings["typography"]["bodyScale"]})} onReset={reset("typography","bodyScale")}/><SelectControl label="Heading weight" value={resolved.typography.headingWeight} options={["medium","semibold"]} onChange={value=>updateGroup("typography",{headingWeight:value as VisualSettings["typography"]["headingWeight"]})} onReset={reset("typography","headingWeight")}/><SelectControl label="Letter spacing" value={resolved.typography.letterSpacing} options={["tight","standard","technical"]} onChange={value=>updateGroup("typography",{letterSpacing:value as VisualSettings["typography"]["letterSpacing"]})} onReset={reset("typography","letterSpacing")}/><SelectControl label="Text tone" value={resolved.typography.textTone} options={["auto","light","dark"]} onChange={value=>updateGroup("typography",{textTone:value as VisualSettings["typography"]["textTone"]})} onReset={reset("typography","textTone")}/></fieldset>
        <fieldset><legend>Media presentation</legend><SelectControl label="Fit" value={resolved.media.fit} options={["source","contain","portrait-frame","editorial-frame","background"]} onChange={value=>updateGroup("media",{fit:value as VisualSettings["media"]["fit"]})} onReset={reset("media","fit")}/><RangeControl label="Focal X" value={resolved.media.focalX} min={0} max={100} onChange={value=>updateGroup("media",{focalX:value})} onReset={reset("media","focalX")}/><RangeControl label="Focal Y" value={resolved.media.focalY} min={0} max={100} onChange={value=>updateGroup("media",{focalY:value})} onReset={reset("media","focalY")}/><SelectControl label="Frame" value={resolved.media.frame} options={["none","hairline","glass","dark"]} onChange={value=>updateGroup("media",{frame:value as VisualSettings["media"]["frame"]})} onReset={reset("media","frame")}/><SelectControl label="Corners" value={resolved.media.cornerStyle} options={["square","subtle"]} onChange={value=>updateGroup("media",{cornerStyle:value as VisualSettings["media"]["cornerStyle"]})} onReset={reset("media","cornerStyle")}/><p className="visual-guardrail">Primary story media remains <strong>contain</strong>; ambient media remains <strong>cover</strong>. Compass and document roles cannot be promoted to crop.</p></fieldset>
        {(page==="footer"||page==="global")&&<fieldset><legend>{page==="global"?"Global footer defaults":"Footer"}</legend><SelectControl label="Surface" value={resolved.footer.surface} options={["solid-dark","glass-dark","transparent-dark"]} onChange={value=>updateGroup("footer",{surface:value as VisualSettings["footer"]["surface"]})} onReset={reset("footer","surface")}/><SelectControl label="Alignment" value={resolved.footer.alignment} options={["split","center"]} onChange={value=>updateGroup("footer",{alignment:value as VisualSettings["footer"]["alignment"]})} onReset={reset("footer","alignment")}/><SelectControl label="Type style" value={resolved.footer.typeStyle} options={["technical","editorial"]} onChange={value=>updateGroup("footer",{typeStyle:value as VisualSettings["footer"]["typeStyle"]})} onReset={reset("footer","typeStyle")}/><RangeControl label="Divider" value={resolved.footer.dividerStrength} min={0} max={100} onChange={value=>updateGroup("footer",{dividerStrength:value})} onReset={reset("footer","dividerStrength")}/><RangeControl label="Panel opacity" value={resolved.footer.panelOpacity} min={0} max={100} onChange={value=>updateGroup("footer",{panelOpacity:value})} onReset={reset("footer","panelOpacity")}/><RangeControl label="Footer blur" value={resolved.footer.blur} min={0} max={48} onChange={value=>updateGroup("footer",{blur:value})} onReset={reset("footer","blur")}/></fieldset>}
        <div className="visual-actions"><button type="submit" disabled={busy}>{editor.operation==="saving"?"Saving…":"Save Draft"}</button><button type="button" disabled={busy} onClick={()=>void request("publish")}>{editor.operation==="publishing"?"Publishing…":"Publish"}</button><button type="button" className="studio-secondary" disabled={!section} onClick={resetSelectedSection}>Reset Section</button><button type="button" className="studio-secondary" onClick={resetSelectedPage}>Reset Page</button><button type="button" className="studio-secondary" onClick={resetToGlobal}>{page==="global"?"Baseline V1":"Reset to Global"}</button></div>
      </form>
      <aside className="visual-preview-panel">
        <div className="visual-preview-heading"><span>Live Working Draft</span><div role="group" aria-label="Preview mode"><button type="button" aria-pressed={previewMode==="composition"} onClick={()=>setPreviewMode("composition")}>Composition</button><button type="button" aria-pressed={previewMode==="full-page"} onClick={()=>setPreviewMode("full-page")}>Full Page</button><Link href={previewHref} target="_blank">Open ↗</Link></div></div>
        {previewMode==="composition"?<article style={variables} {...attributes} className="visual-preview-card"><div className="visual-preview-ambient"/><div className="visual-preview-primary"/><div className="visual-preview-overlay"/><div className="visual-preview-copy"><p>AC / {page.toUpperCase()}</p><h2>{pageLabels[page]}</h2><p>Representative composition showing inherited tokens, surface hierarchy, typography, and media treatment.</p><button type="button">Editorial action</button></div></article>:<iframe ref={iframeRef} className="visual-full-page-preview" title={`${pageLabels[page]} live full page preview`} src={previewHref} onLoad={sendPreview}/>} 
        <dl><div><dt>Scope</dt><dd>{scope}</dd></div><div><dt>Target</dt><dd>{section||"whole page"}</dd></div><div><dt>State</dt><dd>{unsavedChanges?`${unsavedChanges} unsaved`:draftDiffersFromPublished?"Draft Saved":"Published"}</dd></div></dl>
      </aside>
    </div>
  </section>
}

function ResetButton({label,onClick}:{label:string;onClick:()=>void}){return <button type="button" className="visual-reset-field" onClick={onClick} aria-label={`Reset ${label}`}>Reset field</button>}
function RangeControl({label,value,min,max,onChange,onReset}:{label:string;value:number;min:number;max:number;onChange:(value:number)=>void;onReset:()=>void}){const progress=(value-min)/(max-min)*100,style={"--range-progress":`${progress}%`} as CSSProperties;return <div className="visual-control-row"><label>{label}<span><input type="range" value={value} min={min} max={max} style={style} onChange={event=>onChange(Number(event.target.value))}/><output>{value}</output></span></label><ResetButton label={label} onClick={onReset}/></div>}
function SelectControl({label,value,options,onChange,onReset}:{label:string;value:string;options:readonly string[];onChange:(value:string)=>void;onReset:()=>void}){const showSwatch=label==="Accent"||label==="Surface"||label==="Tint";return <div className="visual-control-row"><label>{label}<span className="visual-select-shell">{showSwatch&&<i className="visual-control-swatch" data-swatch={value} aria-hidden="true"/>}<select value={value} onChange={event=>onChange(event.target.value)}>{options.map(option=><option value={option} key={option}>{option}</option>)}</select></span></label><ResetButton label={label} onClick={onReset}/></div>}
