import {createHash} from "node:crypto";import {execFile} from "node:child_process";import {promisify} from "node:util";import {copyFile,mkdir,readdir,readFile,stat,writeFile} from "node:fs/promises";import path from "node:path";import {classifyAsset,detectOrientation,mediaTypeFor,normalizeSourcePath,readImageDimensions,sniffImageExtension} from "./media-ingestion-core.mjs";
const DEFAULT_SOURCE="E:\\Real Estate\\Ảnh\\Up lên website";const root=process.cwd();const output=path.join(root,".dev-data","media-scan");const source=normalizeSourcePath(value("--source")||process.env.MEDIA_SOURCE_DIR||DEFAULT_SOURCE);
const previous=await json(path.join(output,"manifest.json"),{entries:[]}),library=await json(path.join(root,".dev-data","media-library.json"),[]),previousByChecksum=new Map(previous.entries.filter(x=>x.checksum).map(x=>[x.checksum,x]));
async function walk(dir){const entries=await readdir(dir,{withFileTypes:true});return (await Promise.all(entries.map(item=>item.isDirectory()?walk(path.join(dir,item.name)):[path.join(dir,item.name)]))).flat()}
const files=await walk(source);const manifest=[];const previewDir=path.join(output,"previews");await mkdir(previewDir,{recursive:true});
for(const sourcePath of files){
  const info=await stat(sourcePath),extension=path.extname(sourcePath).toLowerCase(),mediaType=mediaTypeFor(extension);
  if(mediaType==="unsupported"){manifest.push({id:createHash("sha256").update(sourcePath).digest("hex").slice(0,16),sourcePath,filename:path.basename(sourcePath),extension,mediaType,mimeType:"application/octet-stream",width:0,height:0,aspectRatio:null,orientation:"unknown",duration:null,fileSize:info.size,detectedContext:"unknown",recommendedService:"general",recommendedSlots:[],confidence:"low",containsPeople:false,possiblePrivateInformation:false,approvedForImport:false,approvedForPublicUse:false,notes:["Unsupported file type ignored."]});continue}
  const buffer=await readFile(sourcePath),checksum=createHash("sha256").update(buffer).digest("hex"),actualExtension=mediaType==="image"?sniffImageExtension(buffer):null;
  let videoMetadata={width:0,height:0,duration:null,frameRate:null,codec:null};if(mediaType==="video")videoMetadata=await probeVideo(sourcePath);const dimensions=mediaType==="image"?readImageDimensions(buffer,extension):videoMetadata;
  const classification=classifyAsset(path.basename(sourcePath),dimensions.width,dimensions.height,info.size);
  const effectiveExtension=actualExtension||extension,mimeType=effectiveExtension===".jpg"||effectiveExtension===".jpeg"?"image/jpeg":effectiveExtension===".png"?"image/png":effectiveExtension===".webp"?"image/webp":effectiveExtension===".avif"?"image/avif":extension===".webm"?"video/webm":extension===".mov"?"video/quicktime":"video/mp4";
  const notes=[...classification.notes];if(mediaType==="image"&&!actualExtension)notes.push("Image signature could not be verified.");if(actualExtension&&actualExtension!==extension&&!(actualExtension===".jpg"&&extension===".jpeg"))notes.push(`File content is ${actualExtension} but the filename uses ${extension}; automatic import is blocked.`);if(mediaType==="video")notes.push("ffprobe is unavailable; duration, dimensions, codec, frame rate, and bitrate require owner tooling.","Do not publish until music and content rights are reviewed.");if(info.size>(mediaType==="video"?8:classification.detectedContext==="owner-portrait"?.5:.2)*1024*1024)notes.push("Exceeds the initial web performance budget.");
  const safeClassification=actualExtension&&actualExtension!==extension?{...classification,approvedForImport:false,approvedForPublicUse:false}:classification;
  const prior=previousByChecksum.get(checksum),imported=library.find(asset=>asset.checksum===checksum),needsConversion=mediaType==="video"&&(!videoMetadata.codec||info.size>8*1024*1024);const defaultStatus=needsConversion?"needs-conversion":"unreviewed";const entry={id:checksum.slice(0,16),checksum,sourcePath,filename:path.basename(sourcePath),extension,mediaType,mimeType,width:dimensions.width,height:dimensions.height,aspectRatio:dimensions.width&&dimensions.height?Number((dimensions.width/dimensions.height).toFixed(4)):null,orientation:detectOrientation(dimensions.width,dimensions.height),duration:videoMetadata.duration,frameRate:videoMetadata.frameRate,codec:videoMetadata.codec,fileSize:info.size,...safeClassification,notes,available:true,status:needsConversion?"needs-conversion":imported?"imported":prior?.status||defaultStatus,importedAssetId:imported?.id||prior?.importedAssetId||null,ownerRole:prior?.ownerRole||null,ownerServiceLens:prior?.ownerServiceLens||null,ownerDecisionAt:prior?.ownerDecisionAt||null};manifest.push(entry);if(mediaType==="image"&&actualExtension&&info.size<=5*1024*1024)await copyFile(sourcePath,path.join(previewDir,`${entry.id}${actualExtension}`))
}
for(const prior of previous.entries.filter(item=>!manifest.some(current=>current.checksum===item.checksum)))manifest.push({...prior,available:false,notes:[...new Set([...(prior.notes||[]),"Source file is no longer available."])]});
await mkdir(output,{recursive:true});await writeFile(path.join(output,"manifest.json"),JSON.stringify({source,scannedAt:new Date().toISOString(),entries:manifest},null,2));const recommendations=manifest.flatMap(entry=>entry.recommendedSlots.map(slot=>({sourceId:entry.id,assetId:null,page:slot.split(".")[0],slot,reason:entry.notes[0],confidence:entry.confidence,cropRisk:entry.orientation==="vertical-9-16"?"high-on-desktop":"medium",mobileSuitability:entry.orientation==="vertical-9-16"?"high":"medium",desktopSuitability:entry.orientation==="vertical-9-16"?"low":"medium",ownerReviewRequired:entry.confidence!=="high"||!entry.approvedForPublicUse})));await writeFile(path.join(output,"assignment-recommendations.json"),JSON.stringify(recommendations,null,2));await writeReport(manifest,recommendations);console.log(`[Media Scan] ${manifest.length} files · ${manifest.filter(x=>x.mediaType==="image").length} images · ${manifest.filter(x=>x.mediaType==="video").length} videos`);
function value(flag){const index=process.argv.indexOf(flag);return index>=0?process.argv[index+1]:null}async function writeReport(entries,recommendations){const dir=path.join(root,"docs","generated");await mkdir(dir,{recursive:true});const counts=(key,value)=>entries.filter(entry=>entry[key]===value).length;const lines=["# Media Assignment Report","",`Generated: ${new Date().toISOString()}`,`Source: \`${source}\``,"",`- Files scanned: ${entries.length}`,`- Images: ${counts("mediaType","image")}`,`- Videos: ${counts("mediaType","video")}`,`- Unsupported: ${counts("mediaType","unsupported")}`,`- Possible private information: ${entries.filter(x=>x.possiblePrivateInformation).length}`,`- High-confidence auto-import candidates: ${entries.filter(x=>x.confidence==="high"&&x.approvedForImport).length}`,"","## Recommendations","",...recommendations.map(item=>`- **${item.slot}** · ${item.confidence} · ${item.reason} · owner review: ${item.ownerReviewRequired?"yes":"no"}`),"","Generated data remains local and must not be committed without explicit approval."];await writeFile(path.join(dir,"MEDIA_ASSIGNMENT_REPORT.md"),lines.join("\n"))}
async function json(file,fallback){try{return JSON.parse(await readFile(file,"utf8"))}catch(error){if(error.code==="ENOENT")return fallback;throw error}}
async function probeVideo(file){try{const {stdout}=await promisify(execFile)("ffprobe",["-v","error","-select_streams","v:0","-show_entries","stream=width,height,codec_name,r_frame_rate:format=duration","-of","json",file]);const data=JSON.parse(stdout),stream=data.streams?.[0]||{},rate=String(stream.r_frame_rate||"").split("/").map(Number);return {width:Number(stream.width)||0,height:Number(stream.height)||0,duration:Number(data.format?.duration)||null,frameRate:rate[1]?rate[0]/rate[1]:null,codec:stream.codec_name||null}}catch{return {width:0,height:0,duration:null,frameRate:null,codec:null}}}
