import {mkdir,readFile,rename,writeFile} from "node:fs/promises";
import path from "node:path";
import {assignmentSchema,type MediaAssignment,type MediaSlotKey,type MediaPresentation} from "@/lib/media/types";
import {LocalMediaStorageProvider} from "@/lib/media/storage";
import {getPublicMediaEligibility} from "@/lib/media/approval";
import {assertMediaAssignmentCompatible} from "@/lib/media/slot-contracts";

const assignmentPath=(root:string)=>path.join(root,".dev-data","media-assignments.json");
const draftPath=(root:string)=>path.join(root,".dev-data","media-draft-assignments.json");
export async function listAssignments(root=process.cwd()):Promise<MediaAssignment[]>{if(process.env.NODE_ENV==="production")return [];try{return assignmentSchema.array().parse(JSON.parse(await readFile(assignmentPath(root),"utf8")))}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return [];throw error}}
export async function assignMedia(slot:MediaSlotKey,assetId:string,presentation:MediaPresentation,root=process.cwd(),replace=false){const provider=new LocalMediaStorageProvider(root);const asset=await provider.getMetadata(assetId);if(!asset)throw new Error("Media asset not found.");assertMediaAssignmentCompatible(asset,slot);if(!getPublicMediaEligibility(asset).eligible)throw new Error("Complete privacy, rights, and public-use review before publishing.");const current=await listAssignments(root),existing=current.find(item=>item.slot===slot);if(existing&&existing.assetId!==assetId&&!replace)throw new Error("Slot already has an assignment. Explicit replacement is required.");const next=[...current.filter(item=>item.slot!==slot),assignmentSchema.parse({slot,assetId,presentation,updatedAt:new Date().toISOString()})];await writeAssignments(next,root);await removeDraftAssignment(slot,root);return next.find(item=>item.slot===slot)!}
export async function removeAssignment(slot:MediaSlotKey,root=process.cwd()){const next=(await listAssignments(root)).filter(item=>item.slot!==slot);await writeAssignments(next,root)}
export async function listDraftAssignments(root=process.cwd()):Promise<MediaAssignment[]>{if(process.env.NODE_ENV==="production")return [];try{return assignmentSchema.array().parse(JSON.parse(await readFile(draftPath(root),"utf8")))}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return [];throw error}}
export async function saveDraftAssignment(slot:MediaSlotKey,assetId:string,presentation:MediaPresentation,root=process.cwd()){if(process.env.NODE_ENV==="production")throw new Error("Draft previews are development-only.");const asset=await new LocalMediaStorageProvider(root).getMetadata(assetId);if(!asset?.imported||asset.possiblePrivateInformation)throw new Error("Draft media must be imported and not marked private.");assertMediaAssignmentCompatible(asset,slot);const current=await listDraftAssignments(root),next=[...current.filter(item=>item.slot!==slot),assignmentSchema.parse({slot,assetId,presentation,updatedAt:new Date().toISOString()})];const file=draftPath(root);await mkdir(path.dirname(file),{recursive:true});const temp=`${file}.tmp`;await writeFile(temp,JSON.stringify(next,null,2),"utf8");await rename(temp,file);return next.find(item=>item.slot===slot)!}
export async function removeDraftAssignment(slot:MediaSlotKey,root=process.cwd()){const next=(await listDraftAssignments(root)).filter(item=>item.slot!==slot);const file=draftPath(root);await mkdir(path.dirname(file),{recursive:true});const temp=`${file}.tmp`;await writeFile(temp,JSON.stringify(next,null,2),"utf8");await rename(temp,file)}
export async function getAssignedMedia(slot:MediaSlotKey,root=process.cwd()){const assignment=(await listAssignments(root)).find(item=>item.slot===slot);if(!assignment)return null;const asset=await new LocalMediaStorageProvider(root).getMetadata(assignment.assetId);return asset&&getPublicMediaEligibility(asset).eligible?{asset,assignment}:null}
export async function getDraftAssignedMedia(slot:MediaSlotKey,root=process.cwd()){const assignment=(await listDraftAssignments(root)).find(item=>item.slot===slot);if(!assignment)return null;const asset=await new LocalMediaStorageProvider(root).getMetadata(assignment.assetId);return asset?.imported&&!asset.possiblePrivateInformation?{asset,assignment}:null}
async function writeAssignments(items:MediaAssignment[],root:string){const file=assignmentPath(root);await mkdir(path.dirname(file),{recursive:true});const temp=`${file}.tmp`;await writeFile(temp,JSON.stringify(items,null,2),"utf8");await rename(temp,file)}
