import {createHash,randomUUID} from "node:crypto";
import {mkdir,readFile,rename,writeFile} from "node:fs/promises";
import path from "node:path";
import {z} from "zod";
import {mediaAssetSchema,mediaRoleSchema,serviceLensSchema,type MediaAsset} from "@/lib/media/types";

export const inboxStatusSchema=z.enum(["unreviewed","ready","imported","duplicate","private","rejected","unsupported","needs-conversion"]);
export const inboxEntrySchema=z.object({id:z.string(),checksum:z.string().optional(),sourcePath:z.string(),sourceFolder:z.string().default(""),filename:z.string(),extension:z.string(),mediaType:z.enum(["image","video","unsupported"]),mimeType:z.string(),width:z.number().default(0),height:z.number().default(0),duration:z.number().nullable().default(null),frameRate:z.number().nullable().default(null),codec:z.string().nullable().default(null),aspectRatio:z.number().nullable().default(null),orientation:z.string().default("unknown"),fileSize:z.number(),detectedContext:z.string().default("unknown"),recommendedService:z.string().default("general"),recommendedSlots:z.string().array().default([]),confidence:z.string().default("low"),possiblePrivateInformation:z.boolean().default(false),notes:z.string().array().default([]),previewUrl:z.string().nullable().default(null),available:z.boolean().default(true),status:inboxStatusSchema.default("unreviewed"),importedAssetId:z.string().nullable().default(null),ownerRole:mediaRoleSchema.nullable().default(null),ownerServiceLens:serviceLensSchema.nullable().default(null),ownerDecisionAt:z.string().nullable().default(null)});
export type MediaInboxEntry=z.infer<typeof inboxEntrySchema>;

const manifestPath=(root:string)=>path.join(root,".dev-data","media-scan","manifest.json");
const libraryPath=(root:string)=>path.join(root,".dev-data","media-library.json");
export async function listInbox(root=process.cwd()){const manifest=JSON.parse(await readFile(manifestPath(root),"utf8"));return inboxEntrySchema.array().parse(manifest.entries.map((entry:Record<string,unknown>)=>({...entry,sourceFolder:path.dirname(String(entry.sourcePath)),previewUrl:entry.mediaType==="image"?`/api/studio/media/inbox?file=${entry.id}`:null})))}
export async function updateInboxDecision(id:string,decision:Pick<MediaInboxEntry,"status"|"ownerRole"|"ownerServiceLens">,root=process.cwd()){const manifest=JSON.parse(await readFile(manifestPath(root),"utf8"));const index=manifest.entries.findIndex((item:{id:string})=>item.id===id);if(index<0)throw new Error("Inbox item not found.");manifest.entries[index]={...manifest.entries[index],...decision,ownerDecisionAt:new Date().toISOString()};await atomic(manifestPath(root),manifest);return inboxEntrySchema.parse({...manifest.entries[index],sourceFolder:path.dirname(manifest.entries[index].sourcePath),previewUrl:`/api/studio/media/inbox?file=${id}`})}
export async function importInboxItem(id:string,role:z.infer<typeof mediaRoleSchema>,serviceLens:z.infer<typeof serviceLensSchema>,root=process.cwd()){const items=await listInbox(root),entry=items.find(item=>item.id===id);if(!entry||!entry.available)throw new Error("Inbox source is unavailable.");if(entry.mediaType==="unsupported")throw new Error("Unsupported files cannot be imported.");if(entry.possiblePrivateInformation||entry.status==="private")throw new Error("Review privacy before importing this item.");const assets=mediaAssetSchema.array().parse(await json(libraryPath(root),[]));const duplicate=assets.find(asset=>asset.checksum===entry.checksum);if(duplicate){await updateInboxDecision(id,{status:"duplicate",ownerRole:role,ownerServiceLens:serviceLens},root);return {asset:duplicate,status:"duplicate" as const};}
 const now=new Date().toISOString(),assetId=randomUUID(),actualExtension=entry.mimeType==="image/png"?".png":entry.mimeType==="image/jpeg"?".jpg":entry.extension.toLowerCase();let filename=`${assetId}${actualExtension}`,url=`/uploads/${filename}`,provider:MediaAsset["provider"]="local";if(entry.mediaType==="video"){filename=entry.filename;url=`/api/studio/media/inbox?file=${entry.id}`;provider="local-inbox"}else{const buffer=await readFile(entry.sourcePath);await mkdir(path.join(root,"public","uploads"),{recursive:true});await writeFile(path.join(root,"public","uploads",filename),buffer,{flag:"wx"})}
 const asset=mediaAssetSchema.parse({id:assetId,filename,originalFilename:entry.filename,sourceFilename:entry.filename,url,provider,mimeType:entry.mimeType,sourceType:entry.mediaType==="video"?"uploaded-video":"uploaded-image",width:entry.width,height:entry.height,duration:entry.duration,fileSize:entry.fileSize,codec:entry.codec,container:entry.extension.replace(/^\./,""),videoReadiness:entry.mediaType==="video"?(entry.status==="needs-conversion"?"review-required":entry.fileSize>8*1024*1024?"oversized":"poster-needed"):"web-ready",title:{en:entry.filename.replace(/\.[^.]+$/,""),vi:""},description:{en:"",vi:""},alt:{en:"",vi:""},caption:{en:"",vi:""},focalPoint:{x:.5,y:.5},cropMode:"contain",mediaRole:role,serviceLens,checksum:entry.checksum||createHash("sha256").update(await readFile(entry.sourcePath)).digest("hex"),tags:tagsFor(role,serviceLens),reviewStatus:"review",possiblePrivateInformation:false,privacyReviewed:false,approvedForPublicUse:false,imported:true,createdAt:now,updatedAt:now});assets.push(asset);await atomic(libraryPath(root),assets);await updateInboxDecision(id,{status:"imported",ownerRole:role,ownerServiceLens:serviceLens},root);const manifest=JSON.parse(await readFile(manifestPath(root),"utf8")),record=manifest.entries.find((item:{id:string})=>item.id===id);record.importedAssetId=asset.id;await atomic(manifestPath(root),manifest);return {asset,status:"imported" as const}}
function tagsFor(role:string,lens:string){const lensTag={homepage:"Homepage",deal:"DEAL",condition:"CONDITION",space:"SPACE",general:"General"}[lens];return [lensTag,role.includes("portrait")?"Owner Portraits":role.includes("video")?"Videos":role.includes("diagram")?"Diagrams":role.includes("background")?"Backgrounds":"Unassigned","Needs Review"]}
async function json(file:string,fallback:unknown){try{return JSON.parse(await readFile(file,"utf8"))}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return fallback;throw error}}
async function atomic(file:string,value:unknown){await mkdir(path.dirname(file),{recursive:true});const temp=`${file}.tmp`;await writeFile(temp,JSON.stringify(value,null,2),"utf8");await rename(temp,file)}
