import { mkdir,readFile,readdir,rename,stat,unlink,writeFile } from "node:fs/promises";
import path from "node:path";
import { mediaAssetSchema,type MediaAsset } from "@/lib/media/types";
import { validateImage } from "@/lib/media/validation";

export interface MediaStorageProvider{upload(file:{buffer:Buffer;filename:string;mimeType:string}):Promise<MediaAsset>;delete(id:string):Promise<void>;getPublicUrl(asset:MediaAsset):string;list():Promise<MediaAsset[]>;getMetadata(id:string):Promise<MediaAsset|null>;updateMetadata(id:string,updates:Partial<Pick<MediaAsset,"title"|"alt"|"caption"|"focalPoint">>):Promise<MediaAsset>}
export class LocalMediaStorageProvider implements MediaStorageProvider{
  constructor(private root=process.cwd()){}
  private get uploadDir(){return path.join(this.root,"public","uploads")}private get staticDir(){return path.join(this.root,"public","media")}private get dataDir(){return path.join(this.root,".dev-data")}private get metadataFile(){return path.join(this.dataDir,"media-library.json")}
  async upload(file:{buffer:Buffer;filename:string;mimeType:string}){const image=validateImage(file.buffer,file.filename,file.mimeType);await mkdir(this.uploadDir,{recursive:true});const id=crypto.randomUUID();const filename=`${id}${image.extension}`;await writeFile(path.join(this.uploadDir,filename),file.buffer,{flag:"wx"});const now=new Date().toISOString();const asset:MediaAsset={id,filename,originalFilename:file.filename,url:`/uploads/${filename}`,provider:"local",mimeType:image.mimeType,width:image.width,height:image.height,fileSize:file.buffer.length,title:{en:"",vi:""},alt:{en:"",vi:""},caption:{en:"",vi:""},focalPoint:{x:.5,y:.5},createdAt:now,updatedAt:now};const assets=await this.readLocal();assets.push(asset);await this.writeLocal(assets);return asset}
  async delete(id:string){const assets=await this.readLocal();const asset=assets.find(item=>item.id===id);if(!asset)return;if(asset.provider!=="local")throw new Error("Versioned static assets cannot be deleted in Studio.");await unlink(path.join(this.root,"public",asset.url));await this.writeLocal(assets.filter(item=>item.id!==id))}
  getPublicUrl(asset:MediaAsset){return asset.url}
  async list(){const stored=await this.readLocal();const uploads=stored.filter(item=>item.provider==="local");const overrides=new Map(stored.filter(item=>item.provider==="static").map(item=>[item.id,item]));const statics=(await this.readStatic()).map(item=>overrides.get(item.id)||item);return [...uploads,...statics]}
  async getMetadata(id:string){return (await this.list()).find(item=>item.id===id)||null}
  async updateMetadata(id:string,updates:Partial<Pick<MediaAsset,"title"|"alt"|"caption"|"focalPoint">>){const assets=await this.readLocal();let index=assets.findIndex(item=>item.id===id);const existing=index>=0?assets[index]:(await this.readStatic()).find(item=>item.id===id);if(!existing)throw new Error("Media asset not found.");const updated=mediaAssetSchema.parse({...existing,...updates,updatedAt:new Date().toISOString()});if(index<0){assets.push(updated);index=assets.length-1}else assets[index]=updated;await this.writeLocal(assets);return updated}
  private async readLocal():Promise<MediaAsset[]>{try{return mediaAssetSchema.array().parse(JSON.parse(await readFile(this.metadataFile,"utf8")))}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return [];throw error}}
  private async writeLocal(assets:MediaAsset[]){await mkdir(this.dataDir,{recursive:true});const temp=`${this.metadataFile}.tmp`;await writeFile(temp,JSON.stringify(assets,null,2),"utf8");await rename(temp,this.metadataFile)}
  private async readStatic(){const files=await walk(this.staticDir);return Promise.all(files.map(async file=>{const info=await stat(file);const relative=path.relative(this.staticDir,file).replaceAll("\\","/");const extension=path.extname(file).toLowerCase();const mimeType=extension===".png"?"image/png":extension===".webp"?"image/webp":extension===".avif"?"image/avif":"image/jpeg";const now=info.mtime.toISOString();return mediaAssetSchema.parse({id:`static:${relative}`,filename:path.basename(file),originalFilename:path.basename(file),url:`/media/${relative}`,provider:"static",mimeType,width:0,height:0,fileSize:info.size,title:{en:path.basename(file,extension),vi:""},alt:{en:"",vi:""},caption:{en:"",vi:""},focalPoint:{x:.5,y:.5},createdAt:now,updatedAt:now})}))}
}
async function walk(directory:string):Promise<string[]>{try{const entries=await readdir(directory,{withFileTypes:true});const nested=await Promise.all(entries.map(entry=>entry.isDirectory()?walk(path.join(directory,entry.name)):/\.(jpe?g|png|webp|avif)$/i.test(entry.name)?[path.join(directory,entry.name)]:[]));return nested.flat()}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return [];throw error}}
