import { z } from "zod";
import {proceduralSceneIdSchema} from "@/lib/media/procedural-scenes";

export const localizedTextSchema=z.object({en:z.string().trim().max(500).default(""),vi:z.string().trim().max(500).default("")});
export const focalPointSchema=z.object({x:z.number().min(0).max(1),y:z.number().min(0).max(1)});
export const mediaSourceTypeSchema=z.enum(["uploaded-image","uploaded-video","procedural-scene","embed","document"]);
export const mediaRoleSchema=z.enum(["owner-portrait","service-portrait","page-portrait","compass-portrait","diagram","compass-diagram","document","document-reference","hero-image","hero-video","ambient-video","story-backdrop","scroll-background-9-16","section-backdrop","section-background","hud-overlay","decorative-motion","editorial-media","article-media","content-image","inline-image","property-image","inspection-image","spatial-analysis-image","video","content-video","background-video","featured-video","video-thumbnail","product-media","social-media","poster","fallback","background","download-asset","logo","general-media"]);
export const serviceLensSchema=z.enum(["homepage","deal","condition","space","general"]);
export const mediaRightsStatusSchema=z.enum(["unreviewed","owner-created","owner-portrait","licensed-third-party","rights-unclear"]);
export const videoReadinessSchema=z.enum(["unknown","source","optimized","web-ready","poster-needed","oversized","incompatible","review-required"]);
export const mediaMimeTypeSchema=z.enum(["image/jpeg","image/png","image/webp","image/avif","image/svg+xml","video/mp4","video/webm","video/quicktime","application/pdf","application/x-ac-scene+json"]);
const mediaAssetObjectSchema=z.object({id:z.string(),filename:z.string(),originalFilename:z.string(),sourceFilename:z.string().default(""),url:z.string(),provider:z.enum(["local","local-inbox","static","procedural","cloudinary","s3","supabase","vercel-blob"]),mimeType:mediaMimeTypeSchema,sourceType:mediaSourceTypeSchema.optional(),sceneId:proceduralSceneIdSchema.optional(),width:z.number().int().nonnegative(),height:z.number().int().nonnegative(),duration:z.number().nonnegative().nullable().default(null),fileSize:z.number().int().nonnegative(),codec:z.string().nullable().default(null),container:z.string().nullable().default(null),bitrate:z.number().nonnegative().nullable().default(null),videoReadiness:videoReadinessSchema.default("unknown"),posterAssetId:z.string().nullable().default(null),title:localizedTextSchema,description:localizedTextSchema.default({en:"",vi:""}),alt:localizedTextSchema,caption:localizedTextSchema,focalPoint:focalPointSchema,cropMode:z.enum(["cover","contain","natural"]).default("contain"),mediaRole:mediaRoleSchema.default("general-media"),serviceLens:serviceLensSchema.default("general"),decorative:z.boolean().default(false),checksum:z.string().optional(),tags:z.string().array().default([]),reviewStatus:z.enum(["ready","review","private"]).default("review"),possiblePrivateInformation:z.boolean().default(false),privacyReviewed:z.boolean().default(false),rightsStatus:mediaRightsStatusSchema.default("unreviewed"),approvedForPublicUse:z.boolean().default(false),imported:z.boolean().default(true),createdAt:z.string(),updatedAt:z.string()});
function inferSourceType(value:z.input<typeof mediaAssetObjectSchema>):z.infer<typeof mediaSourceTypeSchema>{if(value.sceneId||value.provider==="procedural"||value.mimeType==="application/x-ac-scene+json")return "procedural-scene";if(value.mimeType.startsWith("video/"))return "uploaded-video";if(value.mimeType==="application/pdf")return "document";return "uploaded-image"}
export const mediaAssetSchema=mediaAssetObjectSchema.transform(value=>({...value,sourceType:value.sourceType??inferSourceType(value)}));
export type MediaAsset=z.infer<typeof mediaAssetSchema>;
export type MediaSourceType=z.infer<typeof mediaSourceTypeSchema>;
export type MediaRole=z.infer<typeof mediaRoleSchema>;
export type LocalizedText=z.infer<typeof localizedTextSchema>;
export type FocalPoint=z.infer<typeof focalPointSchema>;

export const mediaPresentationSchema=z.object({mode:z.enum(["none","cover","editorial-panel","background-overlay","texture","static-image","scroll-pan-image","scroll-pan-video","subtle-texture"]).default("cover"),fit:z.enum(["source","contain","cover"]).optional(),cropAllowed:z.boolean().optional(),semanticAlignment:z.enum(["center","top","bottom","left","right","portrait-bottom"]).optional(),backgroundBehavior:z.enum(["section","hero","whole-main-page","decorative-layer","ambient-layer"]).optional(),overlayStrength:z.number().min(0).max(.9).default(.35),overlayColor:z.string().default("#111111"),opacity:z.number().min(0).max(1).optional(),brightness:z.number().min(.2).max(2).optional(),contrast:z.number().min(.2).max(2).optional(),saturation:z.number().min(0).max(2).optional(),blur:z.number().min(0).max(32).optional(),tint:z.string().optional(),blendMode:z.enum(["normal","multiply","screen","overlay","soft-light","luminosity"]).optional(),topGradient:z.number().min(0).max(1).default(0),bottomGradient:z.number().min(0).max(1).default(0),panelOpacity:z.number().min(0).max(1).default(0),textShadow:z.boolean().default(false),focalX:z.number().min(0).max(1).default(.5),focalY:z.number().min(0).max(1).default(.5),startPosition:z.number().min(0).max(1).default(0),endPosition:z.number().min(0).max(1).default(1),textContrastMode:z.enum(["light","dark","automatic","section-controlled"]).default("automatic"),enabled:z.boolean().default(true),reducedMotionFallback:z.enum(["none","static-image"]).default("static-image"),autoplay:z.boolean().optional(),loop:z.boolean().optional(),muted:z.boolean().optional(),playsInline:z.boolean().optional(),playbackRate:z.number().min(.25).max(2).optional(),preload:z.enum(["none","metadata","auto"]).optional(),mobileFallbackAssetId:z.string().nullable().optional(),hideDecorativeOnMobile:z.boolean().optional()});
export type MediaPresentation=z.infer<typeof mediaPresentationSchema>;

export const mediaSlots={
  "homepage.heroPortrait":{label:"Homepage Portrait",category:"Homepage",meaningful:true},"homepage.heroBackground":{label:"Homepage Background",category:"Homepage",meaningful:false},"homepage.heroVideo":{label:"Homepage Hero Video",category:"Homepage",meaningful:true},"homepage.ambientScene":{label:"Homepage Ambient Scene",category:"Homepage",meaningful:false},"homepage.featuredMedia":{label:"Homepage Featured Media",category:"Homepage",meaningful:true},"homepage.storyBackdropMobile":{label:"Homepage Mobile Story Backdrop",category:"Homepage",meaningful:false},"homepage.storyBackdropDesktop":{label:"Homepage Desktop Story Backdrop",category:"Homepage",meaningful:false},"homepage.sectionBackground":{label:"Homepage Section Background",category:"Homepage",meaningful:false},"homepage.footerBackground":{label:"Homepage Footer Background",category:"Homepage",meaningful:false},
  "about.heroPortrait":{label:"About Portrait",category:"About",meaningful:true},"about.ambientScene":{label:"About Ambient Scene",category:"About",meaningful:false},"about.editorialMedia":{label:"About Editorial Media",category:"About",meaningful:true},
  "realEstate.heroImage":{label:"Real Estate Hero",category:"Real Estate",meaningful:true},"realEstate.heroVideo":{label:"Real Estate Hero Video",category:"Real Estate",meaningful:true},"realEstate.propertyMedia":{label:"Property Media",category:"Real Estate",meaningful:true},"realEstate.marketExplainer":{label:"Market Explainer",category:"Real Estate",meaningful:true},"realEstate.marketBackdrop":{label:"Market Backdrop",category:"Real Estate",meaningful:false},"realEstate.editorialMedia":{label:"Real Estate Editorial Media",category:"Real Estate",meaningful:true},"realEstate.sectionMotion":{label:"Real Estate Section Motion",category:"Real Estate",meaningful:false},"realEstate.sectionBackground":{label:"Real Estate Section Background",category:"Real Estate",meaningful:false},"realEstate.storyBackdropMobile":{label:"Real Estate Mobile Story Backdrop",category:"Real Estate",meaningful:false},"realEstate.storyBackdropDesktop":{label:"Real Estate Desktop Story Backdrop",category:"Real Estate",meaningful:false},"realEstate.featuredVideo":{label:"Real Estate Featured Video",category:"Real Estate",meaningful:true},
  "homeInspection.heroImage":{label:"Home Inspection Hero",category:"Home Inspection",meaningful:true},"homeInspection.heroVideo":{label:"Home Inspection Hero Video",category:"Home Inspection",meaningful:true},"homeInspection.reportPreview":{label:"Report Preview",category:"Home Inspection",meaningful:true},"homeInspection.educationMedia":{label:"Inspection Education Media",category:"Home Inspection",meaningful:true},"homeInspection.systemDiagram":{label:"System Diagram",category:"Home Inspection",meaningful:true},"homeInspection.sectionBackground":{label:"Inspection Section Background",category:"Home Inspection",meaningful:false},"homeInspection.storyBackdropMobile":{label:"Inspection Mobile Story Backdrop",category:"Home Inspection",meaningful:false},"homeInspection.storyBackdropDesktop":{label:"Inspection Desktop Story Backdrop",category:"Home Inspection",meaningful:false},"homeInspection.featuredVideo":{label:"Inspection Featured Video",category:"Home Inspection",meaningful:true},
  "spatial.heroPortrait":{label:"Spatial Hero Portrait",category:"Spatial Consultation",meaningful:true},"spatial.heroImage":{label:"Spatial Hero Image",category:"Spatial Consultation",meaningful:true},"spatial.compassPortrait":{label:"Compass Portrait",category:"Spatial Consultation",meaningful:true},"spatial.compassDiagram":{label:"Compass Diagram",category:"Spatial Consultation",meaningful:true},"spatial.orientationVisual":{label:"Orientation Visual",category:"Spatial Consultation",meaningful:true},"spatial.educationMedia":{label:"Spatial Education Media",category:"Spatial Consultation",meaningful:true},"spatial.spatialBackdrop":{label:"Spatial Backdrop",category:"Spatial Consultation",meaningful:false},"spatial.sectionMotion":{label:"Spatial Section Motion",category:"Spatial Consultation",meaningful:false},"spatial.sectionBackground":{label:"Spatial Section Background",category:"Spatial Consultation",meaningful:false},"spatial.storyBackdropMobile":{label:"Spatial Mobile Story Backdrop",category:"Spatial Consultation",meaningful:false},"spatial.storyBackdropDesktop":{label:"Spatial Desktop Story Backdrop",category:"Spatial Consultation",meaningful:false},"spatial.featuredVideo":{label:"Spatial Featured Video",category:"Spatial Consultation",meaningful:true},
  "search.searchBackdrop":{label:"Search Backdrop",category:"Search",meaningful:false},
  "articles.archiveBackdrop":{label:"Articles Archive Backdrop",category:"Articles",meaningful:false},
  "videos.heroMedia":{label:"Videos Hero Media",category:"Videos",meaningful:true},"videos.featuredVideo":{label:"Featured Video",category:"Videos",meaningful:true},"videos.archiveBackdrop":{label:"Videos Archive Backdrop",category:"Videos",meaningful:false},
  "guides.heroMedia":{label:"Guides Hero Media",category:"Guides",meaningful:true},"guides.featuredMedia":{label:"Guides Featured Media",category:"Guides",meaningful:true},"guides.archiveBackdrop":{label:"Guides Archive Backdrop",category:"Guides",meaningful:false},
  "contact.heroMedia":{label:"Contact Hero Media",category:"Contact",meaningful:true},"contact.sectionBackground":{label:"Contact Section Background",category:"Contact",meaningful:false},
  "booking.heroMedia":{label:"Booking Hero Media",category:"Booking",meaningful:true},"booking.sectionBackground":{label:"Booking Section Background",category:"Booking",meaningful:false},
  "global.logo":{label:"Global Logo",category:"Global",meaningful:true},"global.ogImage":{label:"Global Social Image",category:"Global",meaningful:true},"global.footerImage":{label:"Global Footer Image",category:"Global",meaningful:false},
} as const;
export type MediaSlotKey=keyof typeof mediaSlots;
export const mediaSlotKeys=Object.keys(mediaSlots) as MediaSlotKey[];
export const assignmentSchema=z.object({slot:z.enum(mediaSlotKeys as [MediaSlotKey,...MediaSlotKey[]]),assetId:z.string(),presentation:mediaPresentationSchema,updatedAt:z.string()});
export type MediaAssignment=z.infer<typeof assignmentSchema>;

export function localizedValue(value:LocalizedText,locale:"en"|"vi"){return value[locale]||value.en||value.vi}
