import Link from "next/link";
import { ArrowDown, ArrowRight } from "lucide-react";
import { notFound } from "next/navigation";
import { ArticleCard, PlaceholderPortrait, ServicePillarCards } from "@/components/cards";
import { activeCredentials } from "@/data/credentials.config";
import { contentForLocale } from "@/lib/content";
import { isLocale } from "@/lib/i18n";

export default async function Home({params}:{params:Promise<{locale:string}>}) { const {locale}=await params;if(!isLocale(locale))notFound();const vi=locale==="vi";const credentials=activeCredentials();return <>
  <section className="hero"><div className="hero-copy"><p className="eyebrow">Anh Cao · Spatial Specialist LLC</p><h1>{vi?<>Mua sáng suốt.<br/>Kiểm tra kỹ hơn.<br/><em>Hài hòa không gian.</em></>:<>Buy Better.<br/>Inspect Smarter.<br/><em>Align Your Space.</em></>}</h1><p className="hero-lede">{vi?"Quyết định về bất động sản không nên chỉ dựa trên một góc nhìn. Khám phá giao dịch, tình trạng vật lý và cách không gian phục vụ cuộc sống.":"Property decisions should not be made from one perspective alone. Explore the deal, the physical condition, and how the space supports the people inside it."}</p><div className="hero-actions"><Link className="button button-accent" href={`/${locale}/services`}>{vi?"Khám phá 3 góc nhìn":"Explore three perspectives"}<ArrowRight/></Link><Link className="quiet-link" href={`/${locale}/about`}>{vi?"Gặp Anh Cao":"Meet Anh Cao"}</Link></div></div><div className="hero-visual"><PlaceholderPortrait label={vi?"Vị trí ảnh chân dung Anh Cao":"Anh Cao portrait placeholder"}/><div className="visual-note"><span>01—03</span><p>{vi?"Giao dịch · Tình trạng · Không gian":"Deal · Condition · Space"}</p></div></div><a href="#services" className="scroll-cue" aria-label="Scroll to services"><ArrowDown/></a></section>
  <section id="services" className="section"><div className="section-heading"><p className="eyebrow">{vi?"Một tài sản · Ba góc nhìn":"One property · Three perspectives"}</p><h2>{vi?"Hiểu toàn diện hơn trước khi quyết định.":"See the whole property before making the move."}</h2><p>{vi?"Mỗi dịch vụ hoạt động độc lập. Anh/Chị có thể chọn đúng góc nhìn cần thiết mà không bị yêu cầu mua kèm dịch vụ khác.":"Each service stands on its own. Choose the perspective you need—without being required to purchase another service."}</p></div><ServicePillarCards locale={locale}/></section>
  <section className="perspective-section"><div className="perspective-intro"><p className="eyebrow">The Anh Cao Perspective</p><h2>{vi?"Tài sản không chỉ là một địa chỉ.":"A property is more than an address."}</h2></div><div className="perspective-list">{[["Deal",vi?"Giá trị giao dịch":"The financial and transactional side."],["Condition",vi?"Những gì tài sản đang thể hiện về mặt vật lý":"What the property is physically telling you."],["Space",vi?"Cách môi trường vận hành cho người sống bên trong":"How the environment functions for the people inside it."]].map(([t,p],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{p}</p></article>)}</div></section>
  <section className="section guides-section"><div className="section-heading row"><div><p className="eyebrow">{vi?"Cẩm nang mới":"Latest guides"}</p><h2>{vi?"Học trước khi quyết định.":"Clarity before commitment."}</h2></div><Link className="quiet-link" href={`/${locale}/guides`}>{vi?"Xem tất cả":"View all guides"}<ArrowRight/></Link></div><div className="article-grid">{contentForLocale(locale).map(item=><ArticleCard key={item.slug} item={item} locale={locale}/>)}</div></section>
  {credentials.length>0&&<section className="credential-bar">{credentials.map(c=><span key={c}>{c}</span>)}</section>}
  <section className="final-cta"><p className="eyebrow">{vi?"Bắt đầu từ mục tiêu của Anh/Chị":"Start with your goal"}</p><h2>{vi?"Anh/Chị đang nhìn tài sản từ góc nào?":"Which perspective do you need today?"}</h2><div className="cta-links"><Link href={`/${locale}/real-estate/buyers`}>{vi?"Tôi muốn mua nhà":"I want to buy"}</Link><Link href={`/${locale}/real-estate/sellers`}>{vi?"Tôi muốn bán nhà":"I want to sell"}</Link><Link href={`/${locale}/home-inspection/request-inspection`}>{vi?"Tôi cần kiểm tra nhà":"I need an inspection"}</Link><Link href={`/${locale}/spatial-consultation/book-consultation`}>{vi?"Tôi muốn tư vấn không gian":"I want a spatial consultation"}</Link></div></section>
  </> }
